### ISSUE TITLE
Hi :-)

### ISSUE THREAD

**Issue by rhuss** [jolokia/jolokia#1]
Hi @ggiamarchi , thanks a lot for adding me to this organization. What a nice pre-Christmas kind of present ;-) 

I'd like to kindly ask whether I could move the projects from https://github.com/jolokia-org which were currently planned to be the successor of https://github.com/rhuss/jolokia . I'm planning to do this during the Christmas break.

Or do you have other plans with this GitHub organization ?

thanks ...

**Comment by ggiamarchi** [comment]
Hi @rhuss, my plan is pretty simple, I'll basically leave the organization. I was waiting for you to join to be sure you have full control on it before leaving. Now I see it is the case, so you're the boss ;)

Long live Jolokia!

**Comment by rhuss** [comment]
@ggiamarchi Awesome, merci beaucoup!
