### ISSUE TITLE
Jolokia does not support Write-only attributes

### ISSUE THREAD

**Issue by xtesch** [jolokia/jolokia#196]
At line 93 of WriteHandler, Jolokia tries to get the attribute before writing to it. This throws an exception if the attribute is write-only. Therefore Jolokia is unable to write to write-only attributes.

https://github.com/rhuss/jolokia/blob/master/agent/core/src/main/java/org/jolokia/handler/WriteHandler.java

**Comment by arnabbiswas1** [comment]
I will take this.
