### ISSUE TITLE
Custom restrictor using JolokiaHttpHandler

### ISSUE THREAD

**Issue by pwielgolaski** [jolokia/jolokia#224]
I wonder what are my options to use custom restrictor when I have already HttpServer setup (sun).
I would like to define my own restrictor, not using policy.

Could we?
- make protected method Restrictor createRestrictor(Configuration pConfig)
- give possibility to define class for restrictor in configuration
- accept restrictor in constructor in similar way as AgentServlet does it

**Comment by rhuss** [comment]
Yes, restrictor should be more extensible (Jolokia 2.0 already will provide the proper hooks)

Since I'm currently on vacations this might take two Wood until I can pick that up. Hope that's OK.

**Comment by nevenr** [comment]
Hi guys,

if you think this change (https://github.com/nevenr/jolokia/commit/94a1ed5f6fa8aa28dc34b84d17e26517b48db788) is good enough I will create PR.

Regards,
N.

**Comment by grgrzybek** [comment]
Closed as fixed here: 94a1ed5f6fa8aa28dc34b84d17e26517b48db788
