### ISSUE TITLE
Empty array handling is broken in the current version of json-simple

### ISSUE THREAD

**Issue by brendan-hofmann** [jolokia/jolokia#226]
When a response containing an empty array is serialized with json-simple, the toString() of a Java array is inserted instead of a valid empty JSON array. This results in an unparseable json response due to the dangling [. There is a fix in json-simple from 2013 (https://code.google.com/p/json-simple/source/detail?r=211) but there hasn't been a release since 2012, and the project seems to be mostly dead.

For completeness' sake, it looks like one of the maintainers exported it here: https://github.com/fangyidong/json-simple including the above-mentioned fix, here: https://github.com/fangyidong/json-simple/commit/e9e14319ab772d482a69b2d496356d20bffa3dac , though there still hasn't been a more recent release.

**Comment by grgrzybek** [comment]
Fixed (works) with #686.
