### ISSUE TITLE
JSR-160 connector

### ISSUE THREAD

**Issue by panda87** [jolokia/jolokia#229]
Hi

Im using Docker containers with JVM based applications in it and I'm looking for Jolokia to be able pull JMX metrics directly from the JSR-160 protocol instead of using agents, for example like CollectD does.
From political reasons I can't add one of the agents into the container so I need something from outside of it to pull those metrics.
In addition, I don't see how we will add another service like Tomcat or Jetty to those servers in order to use the current proxy agents.

Does this possible? or should I wait for another version so this will have the right agent \ collector?

Thanks

**Comment by grgrzybek** [comment]
As long as the docker container image starts a JVM application with remote JMX connector exposed (and available through docker container process), you can use [remote MBeanServer Connection](https://jolokia.org/reference/html/manual/clients.html#client-jmx-adapter).
