### ISSUE TITLE
jolokia-agent.jar is not responding to control commands "InvocationTarget..." exception

### ISSUE THREAD

**Issue by dmitry-wht** [jolokia/jolokia#232]
Another occurrence of "InvocationTarget" from my side, but I expect it is not a permissions issue. 

I successfully started java service (hazelcast) and attached jolokia agent to it under the same UID, 
but after some days jolokia falls in InvocationTarget exception when I try to get it's status. However it is still working.

```
> java -version
java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)
Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed mode)

> java -jar /jar_path/jolokia-jvm-1.3.2-agent.jar status 6046
InvocationTarget class com.sun.tools.attach.VirtualMachine (command: status) : null

> curl 'http://localhost:8779/jolokia/'
{"timestamp":1449759596,"status":200,"request":{"type":"version"},"value":{"protocol":"7.2","config":{"maxDepth":"15","maxCollectionSize":"0","maxObjects":"0","discoveryEnabled":"false","agentContext":"\/jolokia","historyMaxEntries":"10","agentId":"192.168.1.1-6046-43cda81e-jvm","agentType":"jvm","debug":"false","debugMaxEntries":"100"},"agent":"1.3.2","info":{}}}
```

After restart of java service, everything is working fine again. 

> So, try to get that status of a process whose has Jolokia already attached ?

Right, but start/stop commands are not working too. 

> When you curl it, is it this process which answers ?

Yes, there is only one java process on that hosts and no http servers

> What do you mean with 'restarting the service' ? 

I can kill my java process, start it again and attach jolokia agent without issues.

**Comment by dmitry-wht** [comment]
Issue is reproducing ~ once a week

**Comment by rhuss** [comment]
This is probably a regression with Java 6 and the Java Attach API. Could you try to run the status command with `--verbose` so that the stacktrace is printed, too ?

If it is an issue for within the Java 6 JVM we are probably out of luck since Java 6 is end of life since February 2013 and no fixes will happen here. Do you have any chance to upgrade your JVM ? (which btw I would recommend anyways)

**Comment by dmitry-wht** [comment]
[jolokia.log.txt](https://github.com/rhuss/jolokia/files/69561/jolokia.log.txt)
Sorry for delay, have to reproduce issue again. Here is verbose output attached.

Also I tested it on 1.7.0_79 version, looks like issue is not reproduced there. So I also suspect that root cause is in Java 6. But, unfortunately, upgrade it is not up to me.
Thanks

**Comment by rhuss** [comment]
Sorry, I meant 

```
java -jar /jar_path/jolokia-jvm-1.3.2-agent.jar --verbose status 6046
```

(so, the verbose after the jar filename)

**Comment by dmitry-wht** [comment]
Here you are
```
InvocationTarget class com.sun.tools.attach.VirtualMachine (command: stop) : null
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.jolokia.jvmagent.client.util.VirtualMachineHandler.attachVirtualMachine(VirtualMachineHandler.java:66)
        at org.jolokia.jvmagent.client.AgentLauncher.main(AgentLauncher.java:57)
Caused by: com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
        at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:82)
        at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:46)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:195)
        ... 6 more

```

**Comment by malazbw** [comment]
It happens the same for me, when i execute  `curl` 'http://localhost:8779/jolokia/' in the server, it works , but when i try from my side (client side) in java program 
`J4pClient j4pClient = new J4pClient("http://hostname: 8779/jolokia")` it doesn't work.
What should i do ? i didn't find an answer for dmitry-wht issue as well

**Comment by rhuss** [comment]
`"http://hostname: 8779/jolokia` : Is the space between colon and port intentional ?

**Comment by malazbw** [comment]
No, there is no space, and i tried the port 8080, and it didn't work, 
when i do telnet in the server `telnet localhost 8080` i get this result

> Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.

**Comment by rhuss** [comment]
What now, 8080 or 8779 ? Could it be that you bound the agent only to localhost and not to the external IP ? Maybe add a `-host 0.0.0.0` when starting the agent ?

**Comment by grgrzybek** [comment]
Please reopen if it happens again.
