### ISSUE TITLE
Add a 'valueFormat' for the result value of Jolokia operations

### ISSUE THREAD

**Issue by rhuss** [jolokia/jolokia#237]
Currently the `value` property of a Jolokia response is in the simplest case the plain value of the attribute (with a potentially an applied `path`), for mulitple-mbean read requests a more complex structure (object with the MBean names as keys and the requested attributes as a value object. see reference manual).

However this format is a bit cumbersome contemporary for NoSQL databases which uses plain JSON objects to store. So, in order to store the value directly in such system it would be nice if the MBean name could be part of this value object, too.

This issue suggest to introduce a new formatting parameter `valueFormat` as query parameter with the possible values `plain` and `tag`. `plain` means the current behaviour, the new `tag` format puts MBean object name information directly into the value.

For example, a request to `http://localhost:8080/jolokia/read/kafka.log:name=Production,type=Log,*/Value` leads to answer which looks like

``` json
{
    "request": {
        "attribute": "Value",
        "mbean": "kafka.log:name=Production,type=Log,*",
        "type": "read"
    },
    "status": 200,
    "timestamp": 1452071291,
    "value": {
        "kafka.log:name=Production,partition=0,topic=Default,type=Log": {
            "Value": 2
        },
          "kafka.log:name=Production,partition=0,topic=AnotherTopic,type=Log": {
            "Value": 245018
        }
}
```

This is hard to use for databases. Using `valueFormat=tag`, this hierarchical structures gets resolved to an array of plain objects, with the MBean name weaved in as _tags_. So using `http://localhost:8080/jolokia/read/kafka.log:name=Production,type=Log,*/Value?valueFormat=tag` returns the answer in this format

``` json
{
    "request": {
        "attribute": "Value",
        "mbean": "kafka.log:name=Production,type=Log,*",
        "type": "read"
    },
    "status": 200,
    "timestamp": 1452071291,
    "value": [
        {
           "domain" : "kafka.log",
           "name" : "Production",
           "partition" : 0,
           "topic" : "Default",
           "type" : "Log",
           "Value": 2
        }, 
        {
           "domain" : "kafka.log",
           "name" : "Production",
           "partition" : 0,
           "topic" : "AnotherTopic",
           "type" : "Log",
           "Value": 245018
        }
   ]
}
```

As you can see, the MBean ObjectName's properties are resolved to JSON object keys and merged with the attributes requested (`Value` in this example). The synthetic property `domain` is used for the JMX domain. 

In case of a conflict (e.g. when attributes are named the same as an ObjectName property), then the attribute should win. However, this case is considered to be rare, since attributes are normally uppercased, ObjectName properties are lower case.

**Comment by rhuss** [comment]
@panda87, is this approximately what you meant with your feature request ? (which btw I believe would be a real cool addition to Jolokia)

**Comment by panda87** [comment]
Thanks @rhuss, I couldn't describe that better :+1: 
As we spoke the idea behind that is to make the structure more 'json'ish and be able to separate result to different MBeans and different tags.

For any good time series DB, more tags are more preferred.

**Comment by rhuss** [comment]
@panda87 i just worked on this, but still have a question about your use case. What was it exactly ? I darkly remember that you want to push Jolokia data to a fluentd instance. How do you do this technically ?

**Comment by panda87** [comment]
No, I wanted to push data to influxDB.
My problem was that the response format was not pure json, and even when I tried to parse it by myself, I saw that the response is one huge bulk instead of break it to multiple objects.

**Comment by rhuss** [comment]
@panda87 ok, I see the use case. But are you aware that the JSON protocol is deprecated in InfluxDB and will be [removed for the final 1.0 version of influxDB](https://docs.influxdata.com/influxdb/v0.9/write_protocols/json/) ? The preferred format is a plain line based format (much like used by Prometheus), so you probably will need some sort of transformation from Jolokia response -> InfluxDB line format anyway somehow.

I spend some time on the weekend to implement this, but now I'm not really sure whether to include it its benefit is not so much, because:

* increases complexity of handler and configuration
* for 2.0, where the request handler is replacable, it put an extra burden to implement this format, too
* confusion on the response format which can change based on query parameters
* All information required is already available today, and if a transformation is required anyway, there is no much value add. I believe this true in 99% of all cases, e.g. the `timestamp` is also not included in the value and needs to extracted from a top-level response property.
* I would need to update the documentation and rebase the 2.0 branch.

Quite some points to consider, so I'm really not sure whether to continue (although its always hard to throw away stuff, but its also about maintenance).

Any thoughts on this ?

**Comment by rhuss** [comment]
@panda87 any thoughts on the points above, especially whether this JSON format is useful for you even when InfluxDB is going to remove support for JSON data updates ?

**Comment by panda87** [comment]
Thanks @rhuss. InfluxDB has jolokia plugin which knows to parse the JSON received from the jolokia calls and send them as line protocol

**Comment by panda87** [comment]
RE your points above, I'm aware about the changes should done in order to make this happen.
As written above, the ability to split results to small objects instead of one is very powerful especially in InfluxDB which now heavily support on tags as columns.
Not like other TS DB which serialize the tags to one big type

**Comment by grgrzybek** [comment]
After reading into this issue carefully, I've decided to close it.

First and foremost, Jolokia is a "JMX Protocol Adaptor" (yes, _adaptor_, not _adapter_ - see [Protocol Adaptors and Connectors](https://docs.oracle.com/javase/8/docs/technotes/guides/jmx/overview/agent.html#wp998862)).
It means that Jolokia provides "JSON over HTTP" protocol to access MBeans registered within MBeanServer.

If we provide a variant of the response, where MBean's ObjectName's properties are _moved_ to MBeans's attributes, it'd be kind of confusing - we wouldn't simply adapt the response, we'd alter it - potentially in irreversible way.

I'm working on #564 issue, where `list()` response would be cleverly (I hope so) constructed with performance and readibility in mind, but I'm simply not planning these kind of changes.
