### ISSUE TITLE
Unable to run the unit tests of Jolokia

### ISSUE THREAD

**Issue by gnufied** [jolokia/jolokia#242]
I might be missing something but Jolokia's unit tests are kinda hard to run successfully. Even on travis-ci, they seem to be failing for JDK8 configuration.

But locally using jdk8, the tests fail in all weird places depending on where I run them.

**Comment by gnufied** [comment]
I think presence of multiple network interfaces causes some problems for tests. On my laptop I have 5 network interfaces. Apart from `lo`, `eth0`, `wlan0`  I also have `docker0` and `tun0`.

I could get tests to pass in a vagrant image though.

**Comment by rhuss** [comment]
Unit test on `master` should run and do locally. 

On Travis there is indeed an issue with JDK8 where I don't know why the Java JVM itself heap dumps. I also don't have a chance to reproduce this. So I'm fine as long as it runs with OracleJDK 8

For branch 2.0 there as unit test failures on Travis which are about an already bound socket (and which I don't have locally). I will fix that.

@gnufied could you send me the error log you got ? The Jolokia unit tests are, well, not pure unit trests as you already remarked but a bit of a mixture of unit and system/integration tests. However, as long as they still run quick enough I typically don't care much about the difference ;-). However, the danger is higher that the tests fail in different environments. Especially the multicast discovery feature, which is part of the unit tests currently, can fail in certain circumstances, however I would be curious what happened (becasue thats also good to know what can happen somewhere else).

**Comment by gnufied** [comment]
Here is how they are failing for me:

```
simple(org.jolokia.discovery.DiscoveryMulticastResponderTest)  Time elapsed: 2.022 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
        at org.jolokia.discovery.DiscoveryMulticastResponderTest.simple(DiscoveryMulticastResponderTest.java:36)

simple(org.jolokia.discovery.MulticastSocketListenerThreadTest)  Time elapsed: 1.008 sec  <<< FAILURE!
java.lang.AssertionError: Exactly one in message with the send id should have been received expected [1] but found [0]
        at org.jolokia.discovery.MulticastSocketListenerThreadTest.simple(MulticastSocketListenerThreadTest.java:89)

initWithAgentDiscoveryAndGivenUrl(org.jolokia.http.AgentServletTest)  Time elapsed: 1.505 sec  <<< FAILURE!
java.lang.AssertionError: No agent found
        at org.jolokia.http.AgentServletTest.initWithAgentDiscoveryAndGivenUrl(AgentServletTest.java:154)

initWithAgentDiscoveryAndUrlCreationAfterGet(org.jolokia.http.AgentServletTest)  Time elapsed: 1.016 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
        at org.jolokia.http.AgentServletTest.initWithAgentDiscoveryAndUrlCreationAfterGet(AgentServletTest.java:204)

initWithAgentDiscoveryAndUrlLookup(org.jolokia.http.AgentServletTest)  Time elapsed: 1.011 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
        at org.jolokia.http.AgentServletTest.initWithAgentDiscoveryAndUrlLookup(AgentServletTest.java:167)

```

**Comment by rhuss** [comment]
Thanks !

Form the log output could you paste the content between the two "=====================================" lines + the output after "Network interfaces" (if its not confidential, of course). For me interesting especially are the interfaces listed with 'mc: true' which are supposed to support multicasts. You must have at least one interface indicating that it supports multicast, otherwise the test wouldn't have run.

**Comment by rhuss** [comment]
@gnufied I just tuned the test so that it should work even when no multicast request can be send out over any interface. 

Does it work now for you ?

**Comment by gnufied** [comment]
I just pulled and it still doesn't. I have updated the gist (btw - github doesn't seem to be create notifications on secret gists )

**Comment by rhuss** [comment]
damned, it seems that although you could send udp packets to a multicast group address, it never receive a packet on this interface. 

As a last resort, in the test I start a second try with a much increased timeout (30s). If this doesn't help, I'm going to make this test optional as its too fragile and I have no idea how to fix it otherwise.

Could you please give it a last try ?

**Comment by gnufied** [comment]
I did try again by pulling latest code and it fails for me. I have updated the gist I shared with you.

I am going to try and look into this more closely later this week as well and see if I can find something unique about my local setup.

**Comment by grgrzybek** [comment]
All tests work now both in `main` and `2.0` branches.

The problems with `DiscoveryMulticastResponderTest` are related to UDP multicast firewall settings.
For example on Fedora I had to run:
```
# nft add rule inet firewalld filter_IN_FedoraServer_allow ip daddr 239.192.48.84 accept
```
