### ISSUE TITLE
Jolokia read timeout in Java Agent

### ISSUE THREAD

**Issue by asafm** [jolokia/jolokia#246]
Hi,

We've encountered an issue in production where all calls to Jolokia JVM Agent HTTP server failed on read timeout.
I've tried debugging it by turning the Config.debug flag to true via JConsole, running a read call and then calling debugInfo() operation via JConsole but it always returned an empty string.
I also tried running "grep" on "jolokia" on the standard output of my java process with the Jolokia agent attached but found nothing although the debug flag is on.

So my questions are:
1. What tools can I use to debug where the request is stuck?
2. It would have been much convinient if the jolokia logging would go to the same Logback file we have today (via SLF4J) - is there a plan to do that?

The only solution we did was restart the java process. Is there a way to dynamically restart the jvm agent although it was loaded with "-javagent" ?

**Comment by junketer** [comment]
Hi Asaf, did you ever find a solution? We are finding our jolokia service times out also
Regards
Dan

**Comment by rhuss** [comment]
The first step would be to great a thread dump of the process when it is stuck (SIGQUIT) and identify the HTTP thread's status. Unfortunately I can't help much, but if you post it here maybe somebody else could have a look ?

**Comment by rhuss** [comment]
Check for that method https://github.com/rhuss/jolokia/blob/19666b4f4e7950dde8e6bac54395bec7952482cb/agent/jvm/src/main/java/org/jolokia/jvmagent/handler/JolokiaHttpHandler.java#L174 in the dump, it's Jolokia entry point for handling requests.

**Comment by asafm** [comment]
@junketer Sorry, we've since moved to code we wrote which reports the JMX metrics directly where we need by querying MBeanPlatform directly instead of querying from the outside. See https://github.com/logzio/jmx2graphite as an example

**Comment by grgrzybek** [comment]
Closing as out of date.
BTW - if there are timeouts, the tools to use should be `jstack` to get a thread dump (or `kill -3`) and `curl` running from localhost to ensure this is not a problem with networking layer.
