### ISSUE TITLE
Jolokia GET can fails on some complex request

### ISSUE THREAD

**Issue by fbacchella** [jolokia/jolokia#277]
I'm trying to call a remote method that is defined as:

```
public String prepare(String name, Map<String, String> specifics, List<?> args) throws RemoteException, InvocationTargetException;
```

when called with specifics={} and args=["/"], a GET request is send as:

```
http://localhost:2002/jolokia/exec/jrds:type=agent/prepare/jrds.agent.DiskUsage/%7B%7D/!/
```

And that fails as the second argument is a single "/", not an ["/"], and the error message is not helpfull:

```
curl -RLv 'http://localhost:2002/jolokia/exec/jrds:type=agent/prepare/jrds.agent.DiskUsage/%7B%7D/!/'
....
"error":"java.lang.IllegalArgumentException : Cannot parse JSON \/: Unexpected character (\/) at position 0."
```

With a POST, it works:

```
$ curl -RLv http://localhost:2002/jolokia/ -d '{"mbean":"jrds:type=agent","arguments":["jrds.agent.DiskUsage",{},["/"]],"type":"EXEC","operation":"prepare"}' | jq

{
  "request": {
    "mbean": "jrds:type=agent",
    "arguments": [
      "jrds.agent.DiskUsage",
      {},
      [
        "/"
      ]
    ],
    "type": "exec",
    "operation": "prepare"
  },
  "value": "du_",
  "timestamp": 1469627428,
  "status": 200
}
```

**Comment by grgrzybek** [comment]
If it works with `POST`, that's great.

As [the documentation says](https://jolokia.org/reference/html/manual/jolokia_protocol.html#_escaping_rules_in_get_requests):
> […] the recommended approach is to use POST requests if possible. If GET has to be used and escaping may be confusing with the server you used, use p query parameter. For GET requests with path segments, be careful about the escaping rules.
