### ISSUE TITLE
Jolokia agent as standalone application

### ISSUE THREAD

**Issue by ThomasRasmussen** [jolokia/jolokia#280]
Would it be possible to build a runable JAR file so that I can run Jolokia as a service on all servers? We have some customers that do not accept that we deploy the Jolokia javaagent with their application, so I would like to deploy a jolokia service that can then connect to the JMX port of hte service (which is open). JMX is only listening on localhost so I will need to have many jolokias running.

I've currently built a NOOP class that I can run as a application and connect jolokia jvm agent to, but it would be nice if it was possible to deploy a standalone jolokia app.

Thomas

**Comment by Numblesix** [comment]
It could be great if you share your solution im having the same issue.
I was thinking of an endless loop in java with wait() etc..

**Comment by rhuss** [comment]
Actually that is the idea of using the jolokia proxy-mode : https://jolokia.org/reference/html/proxy.html

The idea is that you deploy a jolokia.war on a separate Tomcat and the agent proxies you to plain JSR-160 JMX via RMI.

Sorry for the late answer, issue slipped through somehow ...

Does this answer your question ?

**Comment by Numblesix** [comment]
this would also be a solution but we would like to not add a seperate tomcat/jetty process to the server instead we would like to have a "dummy" java class where the jolokia agent runs in or can be attached to it. 
Hopefully you get the idea

BR

**Comment by rhuss** [comment]
Don't really get your idea. Maybe you can describe your use case a bit ?

Jolokia is typically used as an agent which attached externally without changing the existing application.

The alternative is to start Jolokia programmatically from within your application. For this there is a decent [Spring integration](https://jolokia.org/reference/html/jmx.html#jvm-spring) but you can also simply use the [JolokiaServer](https://github.com/rhuss/jolokia/blob/master/agent/jvm/src/main/java/org/jolokia/jvmagent/JolokiaServer.java) programmatically.

**Comment by Numblesix** [comment]
Sure.
I want to use jolokia with check_mk for monitoring.

We want an "jolokia_agent" running on any server so we dont need to manualy attach it to tomcat/jboss or plain java application. Therefore a standalone agent would be great.

Thanks for the help im no big java user...
BR

**Comment by tadayosi** [comment]
This has been inactive for long time, and meanwhile we've already released Jolokia 2.0. If you think it's still relevant for 2.0, please respond to it with more clarification on your idea. If there are no further activities here, I'd like to close it.

**Comment by grgrzybek** [comment]
I think we can close it.
