### ISSUE TITLE
dist profile fails to build with jdk 8.

### ISSUE THREAD

**Issue by djcoleman** [jolokia/jolokia#286]
Jolokia version 1.3.5
Maven version 3.2.3
JDK 1.8.0_65

When building with the dist profile activated, I get a large number of javadoc errors along the lines of:
`> mvn -DskipTests=true -P dist clean install`
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.1:jar (attach-javadocs) on project jolokia-core: MavenReportException: Error while creating archive:
[ERROR] Exit code: 1 - /home/dc/jolokia/agent/core/src/main/java/org/jolokia/restrictor/policy/MBeanAccessChecker.java:31: error: self-closing element not allowed`
`[ERROR] * <p/>`
`[ERROR] ^`

Workaround:
Add the '-Dadditionalparam=-Xdoclint:none' property to the mvn command.

**Comment by grgrzybek** [comment]
JavaDoc configuration is now fine and `dist` profile works as expected.
