### ISSUE TITLE
Connections Leak when executing high volume of requests

### ISSUE THREAD

**Issue by copernicuswong** [jolokia/jolokia#287]
Although it is possible to configure the connection pool size and the max connection as well as its timeout.  It is still possible to get the exception.

> Timeout waiting for connection from pool caught here: org.jolokia.client.J4pClient.mapException(J4pClient.java:329) org.jolokia.client.J4pClient.execute(J4pClient.java:198) org.jolokia.client.J4pClient.execute(J4pClient.java:168) org.jolokia.client.J4pClient.execute(J4pClient.java:150)

Since in the J4pClient.execute(), the HttpResponse is actually CloseableHttpResponse so I modify my version to close it directly after execution.

> ```
>     try (CloseableHttpResponse response = (CloseableHttpResponse) httpClient.execute(requestHandler.getHttpRequest(pRequest, pMethod, pProcessingOptions)))
>     {
>         JSONAware jsonResponse = extractJsonResponse(pRequest, response);
>         if (!(jsonResponse instanceof JSONObject))
>         {
>             throw new J4pException("Invalid JSON answer for a single request (expected a map but got a " + jsonResponse.getClass() + ")");
>         }
>         return pExtractor.extract(pRequest, (JSONObject) jsonResponse);
>     }
>     catch (IOException | URISyntaxException e)
>     {
>         throw mapException(e);
>     }
> ```

I understand it is not a proper way to do that since the HttpClient can be customized.  Is there a better way to improve on this?

**Comment by rhuss** [comment]
Thanks for pointing that out, I will check the resource handling in the Java client again.

**Comment by copernicuswong** [comment]
Thanks very much for your help in advance!  Let's see what I can help also.

**Comment by copernicuswong** [comment]
>     public JSONAware extractJsonResponse(HttpResponse pHttpResponse) throws IOException, ParseException {
        HttpEntity entity = pHttpResponse.getEntity();
        try {
            JSONParser parser = new JSONParser();
            Header contentEncoding = entity.getContentEncoding();
            if (contentEncoding != null) {
                return (JSONAware) parser.parse(new InputStreamReader(entity.getContent(), Charset.forName(contentEncoding.getValue())));
            } else {
                return (JSONAware) parser.parse(new InputStreamReader(entity.getContent()));
            }
        } finally {
            if (entity != null) {
                entity.consumeContent();
            }
        }
    }`

And `EntityUtils.consume(entity);` should be used instead of `entity.consumeContent();` also... What do you think?

**Comment by grgrzybek** [comment]
Fixed in 6a0ac12d
