### ISSUE TITLE
ClassCastException, when Jolokia response refused by a proxy (OpenShift)

### ISSUE THREAD

**Issue by jeffmaury** [jolokia/jolokia#308]
When a Jolokia request is handled through a proxy (eg OpenShift) this one may refuse the request (403) but may also return a JSON response which schema is different but may have a status field which is not an integer. In that case the Jolokia Java client will issue a ClassCassException because it assumes status field is always an integer.
See https://issues.jboss.org/browse/JBIDE-23869

**Comment by jeffmaury** [comment]
See #292

**Comment by robstryker** [comment]
This specific issue seems to be fixed, ie the class cast exception
