### ISSUE TITLE
Properties of type object are being converted to string via Object.toString()

### ISSUE THREAD

**Issue by abkieling** [jolokia/jolokia#310]
For properties of type object, having what's generated by Object.toString() as value doesn't look ideal. The hash at the end isn't useful to the users. What if we set the class name?

Sample of Camel component property:
```javascript
"propertiesParser": {
  "kind": "property",
  "type": "object",
  "javaType": "org.apache.camel.component.properties.PropertiesParser",
  "deprecated": "false",
  "secret": "false",
  "value": "org.apache.camel.spring.boot.SpringPropertiesParser@26dd8736",
  "description": "To use a custom PropertiesParser" 
}
```

**Comment by grgrzybek** [comment]
The class name used when serializing generic `java.lang.Object` (or any unsupported/non-serializable class) would be misleading, as it'd suggest `java.lang.String` value.
Not everything can be exposed over JMX and what we have now is a compromise. Please reopen if needed.
