### ISSUE TITLE
Fix dead link from documentation to http://labs.consol.de

### ISSUE THREAD

**Issue by apupier** [jolokia/jolokia#314]
there are http://labs.consol.de/jenkins and http://labs.consol.de/sonar/dashboard/index/org.jolokia:jolokia from index.xml file

and there is also one reference in
![image](https://cloud.githubusercontent.com/assets/1105127/24492059/4d79fffc-152a-11e7-9834-28b523f5dfeb.png)

which i don't know how to update

**Comment by apupier** [comment]
Is http://labs.consol.de/jenkins still a thing? Is there something that is replacing it?

for Sonar, we can point to https://sonarcloud.io/project/overview?id=org.jolokia%3Ajolokia

**Comment by grgrzybek** [comment]
Changed to:
![image](https://github.com/jolokia/jolokia/assets/306565/e5960307-600f-428d-9bf5-a37e51970d69)

For now I left references to consol.de and sonar from older news.
