### ISSUE TITLE
Provide the type definition of Jolokia client for TypeScript

### ISSUE THREAD

**Issue by tadayosi** [jolokia/jolokia#321]
TypeScript programmers want `jolokia.d.ts` to work with JavaScript client. It's great if the `d.ts` is provided somewhere like [@types/node](https://github.com/DefinitelyTyped/DefinitelyTyped).

FWIW, hawtio already has a home-brewed `d.ts` here:
https://github.com/hawtio/hawtio-core-dts/blob/v3.0.4/jolokia.d.ts

**Comment by vblagoje** [comment]
I second @tadayosi as this would be a very useful feature for [us](https://github.com/infinispan/infinispan-management-console) as well

**Comment by tadayosi** [comment]
Fixed with #574. The type definitions should be provided once Jolokia 2.0 is released.
