### ISSUE TITLE
Feature Request: Python client

### ISSUE THREAD

**Issue by wbrefvem** [jolokia/jolokia#324]
Some of my colleagues and I are talking about creating better Ansible modules for the JBoss universe, and Jolokia is a natural choice for consuming management data from JMX-capable apps. In order for the module to ship with Ansible, it has to be in python. 

As it happens, there's a great python library for sending HTTP requests and mapping the response data to python primitives, but it would be even better if there was a purpose-built Jolokia client for python. If we're going to write multiple modules, rewriting the Jolokia connection logic every time is problematic, and not just because I'm lazy! Well, okay, it is because I'm lazy. Basically we need a lazy way to connect to Jolokia with python.

If there's an appetite for this, I'm happy to start working on something.

**Comment by rhuss** [comment]
Excellent, thanks for considering Jolokia ;-)

Have you checked, there are already some Jolokia Python libraries out there: 

* https://github.com/cwood/pyjolokia
* https://github.com/jhermann/jmx4py

Maybe they already serve your purpose?

I do not know how good they are as I'm not a Python user. The Jolokia approach wrt. to client libraries so far was that Perl (yeah! :), JavaScript and Java are hosted under the Jolokia umbrella (well, my umbrella :), but I'm super happy to support any other client lib.

Said that there is a big move planned from my personal project to the GitHub `jolokia-org` organisation, where I also want to split up the monolithic Jolokia project into sub-projects. I.e. a repo for each client, and of course want to open this to a wider community.

Unfortunately, the demand (or call it pressure) was not yet high enough to make this big step. But I'm positive to do this anytime soon (if I convince myself to shuffle my not-so-small backlog). So, if you are interested in picking up a Python library and willing to maintain it, I'm super happy to invite you to join 'jolokia-org' for a repo `jolokia-org/client-python`.

**Comment by wbrefvem** [comment]
Thanks! The libraries you linked have some promise, but it looks like they may be abandoned. I'll have to play with them and see if there's anything usable.

I'm honored that you would consider adding me to `jolokia-org`. :) Before I can commit to anything, I need to do some more research/planning. Here are a few questions:

1. Do you have any plans for big changes to Jolokia? 
2. What are some classic use cases for Jolokia? The two that jump out at me are connecting to Tomcat and Karaf, but what about Java EE containers like Wildfly/JBoss AS? Does Jolokia provide anything beyond what the HTTP Management API provides? I need to understand better the relationship between HTTP Management and JMX. It seems to me that it's just two interfaces to the same management system, but maybe I'm wrong. I also notice that Jolokia can be used as a Wildfly Swarm fraction.

Maybe if we get a stable python client going, we can talk about a Node.js client. ;)

**Comment by wbrefvem** [comment]
@rhuss

I think I get it now. JMX is a common standard but most Java EE app servers also implement their own non-standard management APIs that are nowhere near as feature-rich as JMX. Not to mention that fact that Jolokia also supports OSGi and basic servlet containers.

In any case, I see a lot of value in a python client for Jolokia.  I've started planning and preliminary stubbing for a python client, which you can see [here](https://github.com/wbrefvem/python-jolokia). Whenever you're ready, I'm happy to migrate the repo to `jolokia-org` and rename it according to the project's naming conventions. And I can commit to maintaining it. :)

**Comment by rhuss** [comment]
> Do you have any plans for big changes to Jolokia?

Jolokia 2.0 is nearly there (well, it was for the last 2 yrs ;), and as a single big new feature brings support for JMX notifications via SSE and a pull HTTP pull model. Also, the agent has been modularised internally to be more flexible. The good news for clients is that the API is completely backwards compatible.

> What are some classic use cases for Jolokia? The two that jump out at me are connecting to Tomcat and Karaf, but what about Java EE containers like Wildfly/JBoss AS? Does Jolokia provide anything beyond what the HTTP Management API provides? I need to understand better the relationship between HTTP Management and JMX. It seems to me that it's just two interfaces to the same management system, but maybe I'm wrong. I also notice that Jolokia can be used as a Wildfly Swarm fraction.

Jolokia is used in many ways:

* The original use case was for Nagios monitoring (and was originally started as jmx4perl, which provides also a fully featured Nagios plugin)
* It is used as the access layer for generic management UIs like for http://hawt.io/
* Jolokia is also included in OpenShift in the Java base images and a UI is nicely integrated into the OpenShift admin console which communicates with Java application pods via Jolokia
* I know from some quite big companies and organisations (like the CERN) which rely on Jolokia for management access.

But you are right, its a very generic adapter to JMX and which is completely agnostic to the management data it exports and so it is very flexible. Jolokia has an integration test suite which covers almost thirty application servers. For Java 9 things will get interesting again, as the internal modularization of the JVM might become an issue for the Jolokia agent and how JMX is accessed. But this is still in the future.

------

The initial setup looks good, I would also add `search`  and `info` (or `version`) as API methods. 
Some additional ideas which go beyond a plain access API but has been proven as useful e.g. for the JavaScript client:

* A simple scheduler which periodically calls via Jolokia and then reports the results back via callbacks.
* Some sort of data type for response and request for the user to provide
* A 'simple' API layer which take the parameter as method parameters (like in [jmx4perl](https://metacpan.org/pod/JMX::Jmx4Perl#$value-=>-$jmx->get_attribute(...))) and a 'full' API layer which takes `request` objects and returns `response` objects.

I suggest you just start in your personal repo and when the lib is a bit more matured we can move it along to jolokia-org. Is this ok for you ?

thanks a lot for kicking in ...

**Comment by wbrefvem** [comment]
Thanks for the input, that's very helpful.

Couple of questions:

> A simple scheduler which periodically calls via Jolokia and then reports the results back via callbacks.   

By reporting via callbacks, do you mean storing the response data in memory in a global var, or persisting it to some storage medium? I suppose it would be simple enough to give the user the option of specifying a persistence destination, with an in-memory option.   

> * Some sort of data type for response and request for the user to provide   
> * A 'simple' API layer which take the parameter as method parameters (like in jmx4perl) and a 'full' API layer which takes request objects and returns response objects.

This makes sense. I like the `get_attribute` method from jmx4perl, so I'll probably implement one of those. Also, I'll probably start with the simple layer and then go to the full.

**Comment by rhuss** [comment]
> By reporting via callbacks, do you mean storing the response data in memory in a global var, or persisting it to some storage medium? I suppose it would be simple enough to give the user the option of specifying a persistence destination, with an in-memory option.

Actually, I don't know python weel enough, but in the Javascript, a callback function is registered at the scheduler which is periodically called with the results of a specific query. I would not offer any persistence solution, on this lightweight scheduling (where the callback registration is also not persistent). In Perl it's a sub-ref, in Java an object implementing a callback interface.

> This makes sense. I like the get_attribute method from jmx4perl, so I'll probably implement one of those. Also, I'll probably start with the simple layer and then go to the full.

Sounds like a plan ;-) Let me know how it goes and ping me if you need a reviewer.

**Comment by wbrefvem** [comment]
> a callback function is registered at the scheduler which is periodically called with the results of a specific query.    

This sort of thing is a bit more complicated in Python than JavaScript, but I think I found a library that could make it manageable.  

Once I have all my methods implemented and tested, I'll be ready for a review.

**Comment by wbrefvem** [comment]
@rhuss 
I think I'm ready for a code review. I've implemented `get_attribute` and `set_attribute` methods based on jmx4perl. Any feedback you have is much appreciated. :)

**Comment by rhuss** [comment]
Awesome, thanks ! Give me a bit, will have a review soon (but still totally busy with other stuff). Hope I can do it this or next week. If not, please ping me again.

**Comment by wbrefvem** [comment]
Will do.

**Comment by wbrefvem** [comment]
Hey @rhuss any chance to look at this yet? No worries if not, I don't mean to be a pest. :)

**Comment by rhuss** [comment]
Sorry for the delay, still under load. Hope I can have a look this week (but no promises :(

**Comment by wbrefvem** [comment]
Not a problem at all. :) I'm working with some folks to put together a JBoss working group in the Ansible project. There are some folks who are doing similar work to this, so we're trying to coordinate our efforts. Hopefully once that group is up and running, we can get a few more pairs of eyes looking at this.

**Comment by wbrefvem** [comment]
Hey @rhuss, still working on this. I haven't been able to spend much time on it till recently, but I just pushed some updates and published an alpha version to [PyPI](https://pypi.python.org/pypi/jolokia/0.1.0a4) yesterday.

There seems to be a lot of interesting in *using* a Python Jolokia client (>5000 downloads in the first 24 hours), but not much interest in helping to build one, so it's just me for now!

**Comment by rhuss** [comment]
Cool. Sorry for being so unresponsive, it has been a bit calm around Jolokia recently, but I'm planning to pick this us again soon (when my working queue goes down a bit, which might take a bit until May). 

So I hadn't any chance to look into recently, but I hope I can do so soon.

BTW, I finally got hold on the GitHub organization [jolokia](https://github.com/jolokia), and I'm planning to move all Jolokia code this orga + any client libraries which might be interested (that's not mandatory of course). But if you like, I would like to invite you to join this 'orga', too (as soon as I have moved the basic pieces to it).

**Comment by wbrefvem** [comment]
That sounds great. I'd be honored to be a part of the jolokia org. :) Your timetable is actually good, because it'll give me time to stabilize the API. I'll give you updates periodically as appropriate.

**Comment by wbrefvem** [comment]
@rhuss Just wanted to touch base about this. I'm still maintaining the python client. I've got a few PRs here and there, and it seems to have a user base, admittedly very small. I don't think I need any support to keep maintaining it, but if you have any ideas, please let me know.

**Comment by rhuss** [comment]
@wbrefvem sorry for the long delay and a lot has happened in the meantime. Unfortunately, my focus has been drifted quite away (and I'm even not coding in Java anymore currently), so Jolokia is kind of on hold currently. I'm still looking at how to proceed, but I'm afraid that I can't invest any substantial effort currently in Jolokia.

This also means that I won't be able to push to a Jolokia 2.0 which would include the move to the jolokia github.org.

However, if someone or a community is willing to step up for future development on Jolokia, I would be very happy to consider a handover.

Sorry, for now the status is kind of frozen.

**Comment by wbrefvem** [comment]
@rhuss No worries, I'm not coding in Python much anymore! Thanks for the update.

**Comment by tadayosi** [comment]
It looks like this request is abandoned. So let me close this for now. Feel free to open a new feature request when we are ready and want to support a Python client again. Thanks.
