### ISSUE TITLE
Passing string array signature to operations via the java client

### ISSUE THREAD

**Issue by wwfdoink** [jolokia/jolokia#337]
Hi there, is there any way to escape the type name if it contains a ; character.
I'm trying to pass a [Ljava.lang.String; signature for the operation.

```java
execRequest = new J4pExecRequest("com.sun.management:type=DiagnosticCommand",
    "gcClassHistogram([Ljava.lang.String;)",
    new ArrayList<Object>());
J4pExecResponse execResponse = j4pClient.execute(execReq);
```
> {"error":"java.lang.IllegalArgumentException : No operation gcClassHistogram([Ljava.lang.String found on MBean com.sun.management:type=DiagnosticCommand"}

It works fine without signatures and with eg: long[] but their serialized classname don't have a ; character.

**Comment by rhuss** [comment]
Actually, this seems to be an issue of the Java client, which does not URL encode a `;` when using a GET request (so, the URL ends prematurely at the semicolon). It should be encoded with %3B for a GET request.

Could you try with a POST request, too? Alternatively, you could try to replace the ';' with a %3B when creating the exec request.

Actually, URL escaping should be added here, too --> https://github.com/rhuss/jolokia/blob/cc8104062231e246254ad8063217c06cfc28641a/client/java/src/main/java/org/jolokia/client/request/J4pRequestHandler.java#L191

Fancy for sending  a PR ?

**Comment by wwfdoink** [comment]
The POST version works fine out of the box, thanks for helping out.
I'm sorry for the reported problem, i'm using jolokia via an embedded tomcat and it fails with the ;.

I played with the default webserver and it looks like there is a tiny issue using GET with the java client.
https://github.com/rhuss/jolokia/blob/cc8104062231e246254ad8063217c06cfc28641a/client/java/src/main/java/org/jolokia/client/request/J4pRequest.java#L264
It returns "" string if its an empty list and then the url will end up with a slash and you will get the "0 parameter instead of 1" from jolokia.
eg:

> http://localhost:8778/jolokia/exec/com.sun.management:type=DiagnosticCommand/gcClassHistogram(%5BLjava.lang.String%3B)/

Returning with the magic "[null]" or "/" string works fine. Probably the [null] thing looks better since its not a "" and the url doesnt end up with double slashes.
```java
    private String getArrayForArgument(Object[] pArg) {
        if (pArg.length < 1) {
            return "[null]"; // or you can return / then the url ends up with double slashes
        }

        StringBuilder inner = new StringBuilder();
        for (int i = 0; i< pArg.length; i++) {
            inner.append(nullEscape(pArg[i]));
            if (i < pArg.length - 1) {
                inner.append(",");
            }
        }
        return inner.toString();
    }
```
So you will end up with this url and it works fine:

> http://localhost:8778/jolokia/exec/com.sun.management:type=DiagnosticCommand/gcClassHistogram(%5BLjava.lang.String%3B)/%5Bnull%5D

**Comment by rhuss** [comment]
Hmm, not the problem is, how we can distinguish between an empty array and a null array (which are clearly different. The problem with double slashes (which would be used in this case) is, that e.g. Tomcat slurps them in and normalizes them to a single slash. Maybe we need another magic `[empty]` but on the other hand, I really don't like to introduce these magic strings as they can obviously collide with real arguments.

Any suggestions ?

**Comment by wwfdoink** [comment]
From my student perspective i don't really understand why the java-client ever using GET requests :)
On the agent side its trivial and really handy.

**Comment by grgrzybek** [comment]
Java client can be configured to use POST or GET method without problems.
And GET requests are limited because of HTTP/URL restrictions. It's always recommended for complex requests to use POST method.
