### ISSUE TITLE
JAASAuthenticator.checkCredentials does not log exception

### ISSUE THREAD

**Issue by wsargent** [jolokia/jolokia#345]
For the JAASAuthenticator, if there's a LoginException then the login will return false but will not log an exception:

```java
    @Override
    public boolean checkCredentials(String pUser, String pPassword) {
        try {
            final CallbackHandler handler = new UserPasswordCallbackHandler(pUser, pPassword);
            LoginContext loginContext = new LoginContext(realm, handler);
            loginContext.login();
            subjectThreadLocal.set(loginContext.getSubject());
            return true;
        } catch (LoginException e) {
            return false;
        }
    }
```

https://github.com/rhuss/jolokia/blob/d6511446e034818b21c67fed1298de1d24f26cac/agent/jvm/src/main/java/org/jolokia/jvmagent/security/JaasAuthenticator.java#L52

This would be nice for debugging purposes (looking at the debugger I have "javax.security.auth.login.LoginException: unable to find LoginModule class: com.yubico.jaas.YubikeyLoginModule") but I wouldn't know outside of that.

**Comment by rhuss** [comment]
Actually, Jolokia does only very minimal logging and does not e.g. use a logging framework yet. That was a design decision at that time to be as less intrusive as possible. 

I wonder whether we could (and should ?) return an error message to user with the dedicater error message. Alternatively, we might consider using jul-logging for this (but this would be the first time). But maybe even a log to standard error might be ok here. any thoughts ?

btw, I would be very interested about your use case with authenticating Jolokia with Yubi key. Looks like a cool thing ;-)

**Comment by wsargent** [comment]
The least intrusive option is to use JMX's ClassLogger, https://github.com/frohoff/jdk8u-jdk/blob/master/src/share/classes/com/sun/jmx/remote/util/ClassLogger.java

**Comment by wsargent** [comment]
The Yubikey JAAS module is actually pretty trivial -- you need an id2name_textfile defined and it helps to poke at https://github.com/Yubico/yubico-java-client/blob/master/jaas/src/main/java/com/yubico/jaas/YubikeyLoginModule.java#L66 -- but in general you type in the username and hold down the Yubikey, and then it goes off to the Yubikey service and comes back.  The biggest hassle was copying all the trust anchors over from cacerts to a new truststore.

**Comment by mjustin** [comment]
@wsargent Isn't com.sun.jmx.remote.util.ClassLogger an Oracle-specific internal class?

**Comment by wsargent** [comment]
@mjustin I said "least intrusive" -- you can see how the util code works.  Personally I'd use slf4j-api as almost everything uses that, and you can use a jul-slf4j bridge from there if you don't want to use logback or log4j2.

**Comment by rhuss** [comment]
Jolokia has only a single dependency which is json-simple. That way we can keep the agent jar small (~400k). I won't sacrifice this for adding enhanced logging.

Said, that, I think using jul for logging might make sense (instead of printing out to stderr on our own). Let me check whether we can go down this route .. (or whether to stick to stderr).
