### ISSUE TITLE
Unable to read mbeans from remote node

### ISSUE THREAD

**Issue by pmandala** [jolokia/jolokia#349]
Jolokia version :1.3.7

I configured via Jolokia agent servlet in our application which is deployed in Node A of Jetty server  and trying to read jmx beans in another remote Node B using proxy request as follows- 

**Web.xml**
```xml
     <servlet>
      <servlet-name>jolokia-agent</servlet-name>
      <servlet-class>org.jolokia.http.AgentServlet</servlet-class>
      <load-on-startup>1</load-on-startup>
      <init-param>
            <param-name>debug</param-name>
            <param-value>true</param-value>
        </init-param>
    </servlet>

    <servlet-mapping>
      <servlet-name>jolokia-agent</servlet-name>
      <url-pattern>/jolokia/*</url-pattern>
    </servlet-mapping>
```

**Javacript**

```javascript
var data = {
                "type": "read",
                "mbean": "kafka.server:type=BrokerTopicMetrics,name=BytesInPerSec",
                "attribute" : "Count",
                "target": { "url":"service:jmx:rmi:///jndi/rmi://xx.xxx.xxx.xx:xxxx/jmxrmi" }
            };
var jolokia = new Jolokia({url: "./jolokia", method: "post"}); 
jolokia.request(data);
```

If i set target url to invalid hostname, request never fails.

Using JConsole I am able connect using above host name & port

What am I missing here?  Thanks

**Comment by rhuss** [comment]
Could you try first to use a direct request to your JMX proxy (e.g. via postman from within the browser or via curl) ? Does this work ? Could you also try a well known MBean like in the example of https://jolokia.org/reference/html/protocol.html#protocol-proxy ?

**Comment by pmandala** [comment]
curl -X GET http://10.252.136.101:1080/oehcsui/jolokia/read/java.lang:type=Memory/HeapMemoryUsage/  -H 'authorization: Basic YWRtaW46V2VsY29tZS0x'

{"request":{"mbean":"java.lang:type=Memory","attribute":"HeapMemoryUsage","type":"read"},"value":{"init":247463936,"committed":240648192,"max":3504865280,"used":61753920},"timestamp":1505908386,"status":200}


curl -X POST http://10.252.136.101:1080/oehcsui/jolokia/ -H 'authorization: Basic YWRtaW46V2VsY29tZS0x' -d '{ "type": "READ", "mbean" : "java.lang:type=Memory", "attribute" : "HeapMemoryUsage", "target": { "url":"service:jmx:rmi:///jndi/rmi://10.252.137.86:9098/jmxrmi" } }'

{"request":{"mbean":"java.lang:type=Memory","attribute":"HeapMemoryUsage","type":"read","target":{"url":"service:jmx:rmi:\/\/\/jndi\/rmi:\/\/10.252.137.86:9098\/jmxrmi"}},"value":{"init":247463936,"committed":240648192,"max":3504865280,"used":63001864},"timestamp":1505908548,"status":200}

**Exception Curl**

curl -X POST http://10.252.136.101:1080/oehcsui/jolokia/ -H 'authorization: Basic YWRtaW46V2VsY29tZS0x' -d '{"type": "READ","mbean": "kafka.server:type=BrokerTopicMetrics,name=BytesInPerSec", "attribute" : "Count", "target": { "url":"service:jmx:rmi:///jndi/rmi://10.252.137.86:9098/jmxrmi" } }'
{"request":{"mbean":"kafka.server:name=BytesInPerSec,type=BrokerTopicMetrics","attribute":"Count","type":"read","target":{"url":"service:jmx:rmi:\/\/\/jndi\/rmi:\/\/10.252.137.86:9098\/jmxrmi"}},"stacktrace":"javax.management.InstanceNotFoundException: kafka.server:type=BrokerTopicMetrics,name=BytesInPerSec\n\tat com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)\n\tat com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:643)\n\tat com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)\n\tat org.jolokia.handler.ReadHandler.doHandleRequest(ReadHandler.java:106)\n\tat org.jolokia.handler.ReadHandler.doHandleRequest(ReadHandler.java:37)\n\tat org.jolokia.handler.JsonRequestHandler.handleRequest(JsonRequestHandler.java:89)\n\tat org.jolokia.backend.MBeanServerExecutorLocal.handleRequest(MBeanServerExecutorLocal.java:109)\n\tat org.jolokia.backend.MBeanServerHandler.dispatchRequest(MBeanServerHandler.java:161)\n\tat org.jolokia.backend.LocalRequestDispatcher.dispatchRequest(LocalRequestDispatcher.java:99)\n\tat org.jolokia.backend.BackendManager.callRequestDispatcher(BackendManager.java:413)\n\tat org.jolokia.backend.BackendManager.handleRequest(BackendManager.java:158)\n\tat org.jolokia.http.HttpRequestHandler.executeRequest(HttpRequestHandler.java:197)\n\tat org.jolokia.http.HttpRequestHandler.handlePostRequest(HttpRequestHandler.java:137)\n\tat org.jolokia.http.AgentServlet$3.handleRequest(AgentServlet.java:420)\n\tat org.jolokia.http.AgentServlet.handleSecurely(AgentServlet.java:301)\n\tat org.jolokia.http.AgentServlet.handle(AgentServlet.java:277)\n\tat org.jolokia.http.AgentServlet.doPost(AgentServlet.java:244)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:707)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:838)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)\n\tat org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)\n\tat org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)\n\tat org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)\n\tat org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)\n\tat com.oracle.oehcs.web.DefaultFilter.doFilter(DefaultFilter.java:126)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1613)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:541)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1584)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1130)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:564)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:318)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)\n\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)\n\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)\n\tat org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)\n\tat org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)\n\tat org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)\n\tat org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)\n\tat org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)\n\tat java.lang.Thread.run(Thread.java:748)\n","error_type":"javax.management.InstanceNotFoundException","error":"javax.management.InstanceNotFoundException : kafka.server:type=BrokerTopicMetrics,name=BytesInPerSec","status":404}

**Comment by pmandala** [comment]
I debugged and noticed that new MBeanServerConnection is not created for target url parameter.

**Comment by pmandala** [comment]
I am able connect & query `jconsole via remote process` and `remote program using JMXServiceURL` 

**List Operation**

``
curl -X POST http://10.252.136.101:1080/oehcsui/jolokia/?maxDepth=2 -H 'authorization: Basic YWRtaW46V2VsY29tZS0x' -d '{ "type": "LIST", "target": { "url":"service:jmx:rmi:///jndi/rmi://10.252.137.86:9098/jmxrmi" } }'
``


``{"request":{"type":"list","target":{"url":"service:jmx:rmi:\/\/\/jndi\/rmi:\/\/10.252.137.86:9098\/jmxrmi"}},"value":{"JMImplementation":{"type=MBeanServerDelegate":"1"},"java.util.logging":{"type=Logging":"1"},"java.lang":{"name=PS Scavenge,type=GarbageCollector":"1","type=Threading":"1","name=PS Old Gen,type=MemoryPool":"1","type=Memory":"1","name=Metaspace,type=MemoryPool":"1","name=PS Survivor Space,type=MemoryPool":"1","type=OperatingSystem":"1","name=PS Eden Space,type=MemoryPool":"1","name=CodeCacheManager,type=MemoryManager":"1","name=Code Cache,type=MemoryPool":"1","name=Compressed Class Space,type=MemoryPool":"1","type=ClassLoading":"1","type=Compilation":"1","name=PS MarkSweep,type=GarbageCollector":"1","name=Metaspace Manager,type=MemoryManager":"1","type=Runtime":"1"},"com.sun.management":{"type=HotSpotDiagnostic":"1","type=DiagnosticCommand":"1"},"jmx4perl":{"type=Config":"1"},"java.nio":{"name=direct,type=BufferPool":"1","name=mapped,type=BufferPool":"1"},"jolokia":{"type=Discovery":"1","type=ServerHandler":"1","type=Config":"1"}},"timestamp":1506018859,"status":200}``

**Comment by grgrzybek** [comment]
@pmandala simply kafka MBeans are not available...
Please reopen if you want to provide more details.
