### ISSUE TITLE
OSGi exports missing org.jolokia.osgi.security

### ISSUE THREAD

**Issue by kwesterfeld** [jolokia/jolokia#359]
I am attempting to use a fragment bundle to augment the jolokia authentication using "org.jolokia.authClass" property, and in order to do that my bundle must import org.jolokia.osgi.security.   Unfortunately, this does not work since the org.jolokia.osgi bundle does not export this.

Please fix this in a future build.

Thanks!

**Comment by grgrzybek** [comment]
Looks like the export was added here: https://github.com/jolokia/jolokia/commit/1441b0df476e7bb5728d32210e13d18aaaa783cb#diff-ef0ab022a252f080b5764ac4382164edc222a6658e5b7b57b098e965e5ae49f1
