### ISSUE TITLE
Throw exception in Java client when URL length is too long for GET type instead of sending url which will be truncated

### ISSUE THREAD

**Issue by apupier** [jolokia/jolokia#360]
here is the error message:

> Error: java.lang.IllegalArgumentException : Invalid number of operation arguments. Operation addOrUpdateRoutesFromXml(java.lang.String) on org.apache.camel:context=contextToTestJMX,name="contextToTestJMX",type=context requires 1 parameters, not 3 as given

here is the J4pExecRequest:
![image](https://user-images.githubusercontent.com/1105127/32949916-cc181dae-cba4-11e7-9a18-0542fdf13b78.png)
We can notice the single argument.

issue can be reproduced by launching org.fusesource.ide.launcher.tests.integration.remote.debug.RemoteCamelLaunchConfigurationDelegateOverJolokiaIT from this branch: https://github.com/apupier/jbosstools-fuse/tree/FUSETOOLS-2652-FixRouteEditionWhenUsingJolokiaJMXConnection

I tried with GET and POST.

I wasn't able to reproduce with simpler test (yet)

**Comment by rhuss** [comment]
@apupier you are not serious about sending such a large argument via a GET request within the URL path, aren't you? This can lead to all sorts of issue, like even going over an URL size limit of 1024 bytes. For `exec` request with non-trivial parameters, you should always use POST (and maybe even for other requests, too, as POST is far better with encoding / decoding parameters)

I highly recommend using POST for this use case (and I won't going to analyse why the encoding fails for this script to). Happy to take a PR, though, but I don't think its a very good use case to use GET for such kind of request.

Happy to help if it doesn't work for POST, too (as you mentioned above, but would be awesome if you could check this the same way as for the GET post).

**Comment by apupier** [comment]
> you are not serious about sending such a large argument via a GET request within the URL path, aren't you?

I'm reusing what is provided in Jboss tools UI

> This can lead to all sorts of issue, like even going over an URL size limit of 1024 bytes.
I expect an error thrown in this case explaining limitations of GET over POST

> you should always use POST
so you are suggesting that in this case GET is used. So maybe the problem is that "GET" is used although I'm expecting POST used (this is how I configured the connection in JBoss tools UI)

**Comment by apupier** [comment]
yeah found, JBoss Tools is not respecting the Get/POST type for several actions.
So I need to fix it there.

I rename this one to "throw exception when URL length is too long for GET type"

**Comment by rhuss** [comment]
Actually, it was an unfortunate decision at that time to use GET as default. Should have been POST as this is much more capable. So we might change this for Jolokia 2.

Thanks, I'll try to investigate this but actually its not really that there is a fixed limit in an URL length. Only that it gets more likely that some serialization issues are triggered in one of many layers.

So I guess there is no good solution for this right now.

**Comment by grgrzybek** [comment]
I see https://issues.redhat.com/browse/JBIDE-25428 is fixed and POST requests are explicitly mentioned as _recommended_.
I'd close and reopen only if needed.
