### ISSUE TITLE
using jolokia war on Jira | java.io.FileNotFoundException: JAR entry !/META-INF/simplifiers-default not found

### ISSUE THREAD

**Issue by pierrick-openIT** [jolokia/jolokia#369]
Hi,
i try to active jolokia on Jira ...some one has already had this error ?

just copy war file on :  /opt/atlassian/jira/webapps and try to open http://localhost:8080/jolokia/version

---------------------------------------------------------------------------------------------------------

`Etat HTTP 500 - Servlet.init() for servlet jolokia-agent threw exception

type Rapport d''exception

message Servlet.init() for servlet jolokia-agent threw exception

description Le serveur a rencontré une erreur interne qui l''a empêché de satisfaire la requête.

exception

javax.servlet.ServletException: Servlet.init() for servlet jolokia-agent threw exception
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:745)

cause mère

java.lang.IllegalStateException: Cannot load service null defined in jar:war:file:/opt/atlassian/jira/webapps/jolokia.war*/WEB-INF/lib/jolokia-core-1.3.7.jar!/!/META-INF/simplifiers-default : java.io.FileNotFoundException: JAR entry !/META-INF/simplifiers-default not found in /opt/atlassian/jira/temp/jar_cache1023441928551665534.tmp. Aborting
	org.jolokia.util.ServiceObjectFactory.readServiceDefinitionFromUrl(ServiceObjectFactory.java:109)
	org.jolokia.util.ServiceObjectFactory.readServiceDefinitions(ServiceObjectFactory.java:78)
	org.jolokia.util.ServiceObjectFactory.createServiceObjects(ServiceObjectFactory.java:63)
	org.jolokia.converter.json.ObjectToJsonConverter.addSimplifiers(ObjectToJsonConverter.java:350)
	org.jolokia.converter.json.ObjectToJsonConverter.<init>(ObjectToJsonConverter.java:80)
	org.jolokia.converter.Converters.<init>(Converters.java:45)
	org.jolokia.backend.BackendManager.init(BackendManager.java:326)
	org.jolokia.backend.BackendManager.<init>(BackendManager.java:130)
	org.jolokia.backend.BackendManager.<init>(BackendManager.java:105)
	org.jolokia.http.AgentServlet.init(AgentServlet.java:140)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:745)

cause mère

java.io.FileNotFoundException: JAR entry !/META-INF/simplifiers-default not found in /opt/atlassian/jira/temp/jar_cache1023441928551665534.tmp
	sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:142)
	sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:150)
	java.net.URL.openStream(URL.java:1045)
	org.jolokia.util.ServiceObjectFactory.readServiceDefinitionFromUrl(ServiceObjectFactory.java:90)
	org.jolokia.util.ServiceObjectFactory.readServiceDefinitions(ServiceObjectFactory.java:78)
	org.jolokia.util.ServiceObjectFactory.createServiceObjects(ServiceObjectFactory.java:63)
	org.jolokia.converter.json.ObjectToJsonConverter.addSimplifiers(ObjectToJsonConverter.java:350)
	org.jolokia.converter.json.ObjectToJsonConverter.<init>(ObjectToJsonConverter.java:80)
	org.jolokia.converter.Converters.<init>(Converters.java:45)
	org.jolokia.backend.BackendManager.init(BackendManager.java:326)
	org.jolokia.backend.BackendManager.<init>(BackendManager.java:130)
	org.jolokia.backend.BackendManager.<init>(BackendManager.java:105)
	org.jolokia.http.AgentServlet.init(AgentServlet.java:140)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:745)

note La trace complète de la cause mère de cette erreur est disponible dans les fichiers journaux de Apache Tomcat/8.5.6.
Apache Tomcat/8.5.6`

**Comment by dodok1** [comment]
Why not use prepared [Jolokia Agent for Jira](https://marketplace.atlassian.com/1213211)

**Comment by rhuss** [comment]
btw, would be happily take a PR to backport needed changes here into upstream.

**Comment by grgrzybek** [comment]
I'm closing this one. WAR Agent is well tested and all the service descriptors should be found.
Please reopen if needed.
