### ISSUE TITLE
Documentation not clear about multiple arguments in an exec request

### ISSUE THREAD

**Issue by wimsymons** [jolokia/jolokia#380]
Hi,

I found that the documentation is not clear about multiple arguments in an exec request as documented on https://jolokia.org/reference/html/protocol.html#exec.

The format says `/arg1/arg2/...` while Table 6.6 states `<arg1>,<arg2>, ...` and the example `"true","true"`

Which one is it?

Other than that, Jolokia is a great product! Keep up the good work 👍

**Comment by tadayosi** [comment]
Hi,

The format actually says `/<arg1>/<arg2>/...` and the table header states it's the **Part**, which means each `<...>` corresponds to each part of `<...>,<...>, ...`. So I think it's clear enough.

Maybe we can make it a bit more clear at the example, which should be `"true"`,`"true"` or `/true/true/...`.

**Comment by wimsymons** [comment]
Nice, thank you!
