### ISSUE TITLE
Thorntail 2.1.0 doesn't work with latest Jolokia

### ISSUE THREAD

**Issue by rhuss** [jolokia/jolokia#389]
According to https://github.com/fabric8io/fabric8-maven-plugin/issues/1363 the Thorntal logging subsystem is again broken (was fixed for Swarm in 1.3.6)

It needs to be reproduced locally and then fixed for a future Jolokia version.

**Comment by grgrzybek** [comment]
It doesn't look like Jolokia issue, closing. But feel free to reopen with more details ;)
