### ISSUE TITLE
CleanupThread causes memory leak

### ISSUE THREAD

**Issue by sebdehne** [jolokia/jolokia#399]
If the CleanupThread encounters a non-daemon Thread which runs for a long time, then CleanupThread does not make any progress and keeps a reference to all other threads which might have terminated in the mean time. This is preventing GC from reclaiming memory.

**Comment by rhuss** [comment]
Good find. I will try to tackle that asap, but I'm also tacking pull requests. As I'm quite busy with day-to-day work, this would be probably faster.

**Comment by sebdehne** [comment]
Roland, I can write a pull request, but I am wondering why you are not using `Runtime.getRuntime().addShutdownHook()` instead of trying to figuring out shutdown time yourself?

**Comment by rhuss** [comment]
It was quite some time ago when I implemented it and I remember darkly that there was an issue with a shutdown hook (might be specific when running as an agent). But as this was really several years back (maybe even Java for 6), that might not be valid anymore.

**Comment by rhuss** [comment]
Said that, it would be for sure worth a try to switch to a shutdown hook.
