### ISSUE TITLE
Exceptions are not logged

### ISSUE THREAD

**Issue by adrian-baker** [jolokia/jolokia#405]
Unsure if this is the right layer to log, but I was suprised to see this code in org.jolokia.http.HttpRequestHandler#getErrorJSON:

```
        if (backendManager.isDebug()) {
            backendManager.error("Error " + pErrorCode,pExp);
        }
```

**Comment by rhuss** [comment]
Actually, you get exception and errors back to the caller, too.

This code, however, is part of the extra 'debug' functionality which allows you to store errors in the agent memory (and other log events) and can be retrieved the REST API. Not sure whether this is a much-used feature anyway.

The agent itself is stateless and location-unaware, so it does not log to the file system, but only in memory if desired. So it makes only sense to log, if this feature is switched on.

**Comment by grgrzybek** [comment]
I agree with Roland. This works as designed.
