### ISSUE TITLE
How to add a new line in JMX response?

### ISSUE THREAD

**Issue by smuky** [jolokia/jolokia#411]
I am using Spring boot admin with jolokia jmx and I need the response to be with several lines for a clarity.
Unfortunately all my approaches for having a new line failed.
Is there a way to get the response print with new lines?

**Comment by grgrzybek** [comment]
Jolokia returns JSON responses with `text/plain` or `application/json` MIME type (configurable with `mimeType` config option).
It is not supposed to additionally format the output - it's up to the consuming party to present the JSON in whatever form is suitable.
