### ISSUE TITLE
Jakarta Servlet API 5.0+

### ISSUE THREAD

**Issue by ExtraCrafTX** [jolokia/jolokia#451]
The servlet API is moving to the jakarta namespace from javax.
https://jakarta.ee/specifications/servlet/5.0/

Would be great to get a release for the new namespace.

**Comment by grgrzybek** [comment]
The discussion issue: #555

**Comment by grgrzybek** [comment]
yikes. The problem with Spring support for Jolokia 2.0 is that while we want Servlet API 5+ (`jakarta.servlet` package) we still want JDK 11...
However there's no Spring Framework version using JakartaEE 9+ while still being JDK11 compliant...

**Comment by tadayosi** [comment]
@grgrzybek 

> yikes. The problem with Spring support for Jolokia 2.0 is that while we want Servlet API 5+ (`jakarta.servlet` package) we still want JDK 11... However there's no Spring Framework version using JakartaEE 9+ while still being JDK11 compliant...

Yes, [Spring Boot 3 supports only Java 17+.](https://docs.spring.io/spring-boot/docs/current/reference/html/getting-started.html#getting-started.system-requirements) I don't think it's a problem though; we can just support Java 11, 17, ... and Spring Boot can utilise Jolokia 2.0 with Java 17+. The only thing we need to do is just turn off the Spring Boot related subprojects for Java 11, as enabling them for Java 11 doesn't make sense.

**Comment by grgrzybek** [comment]
Sure - I'll add proper Maven profiles.

**Comment by tadayosi** [comment]
Awesome! :tada:
