### ISSUE TITLE
DelegatingAuthenticator's JsonPathExtractor includes an InputStreamReader that is not always closed on method exit.

### ISSUE THREAD

**Issue by ryandgoulding** [jolokia/jolokia#457]
Per https://lgtm.com/projects/g/rhuss/jolokia/snapshot/5af274c465d19828fdbb4f5787b92d5d4cad7539/files/agent/jvm/src/main/java/org/jolokia/jvmagent/security/DelegatingAuthenticator.java?sort=name&dir=ASC&mode=heatmap#x55c5943e509c9609:1

**Comment by grgrzybek** [comment]
Fixed in 20a8d2b7fb020c9aae3e9d7a089edc454d92ccce
