### ISSUE TITLE
jboss eap 7 - WFLYCTL0030  

### ISSUE THREAD

**Issue by marcelkoenig** [jolokia/jolokia#463]
Hello,

we use jolokia-1.6.2.war in JBoss to monitor the application.

With JBoss EAP 6.4 everything works without errors.
With JBoss EAP 7.3 we get the following error every time we start JBoss:

12:34:07,820 ERROR [org.jboss.as.controller.management-operation] (ServerService Thread Pool -- 91) WFLYCTL0013: Operation ("read-resource-description") failed - address: ([
    ("subsystem" => "resource-adapters"),
    ("resource-adapter" => " ldap-resource-adapter"),
    ("connection-definitions" => "ldap-connection-pool"),
    ("statistics" => "extended")
]) - failure description: "WFLYCTL0030: No resource definition is registered for address [
    (\"subsystem\" => \"resource-adapters\"),
    (\"resource-adapter\" => \"ldap-resource-adapter\"),
    (\"connection-definitions\" => \"ldap-connection-pool\"),
    (\"statistics\" => \"extended\")
]"

After startup, jolokia and the application runs without errors.
If I deploy jolokia only after JBoss startup, the error does not come.

I tried to add a dependency in Jolokia to the resource-adapter via the web.xml and the jboss-deployment-structure.xml, but this did not solve the problem.
Also with jolokia-agent-war-2.0.0-M3.war the error comes.

I guess Jolokia polls the MBeans before the JBoss is fully loaded and that's where the error comes from?
Is there any way to set a delay in Jolokia before triggering the JBoss MBean?

Do you have any idea how I can solve this problem?

Thanks a lot
Marcel

**Comment by tadayosi** [comment]
This has been inactive for long time, and meanwhile we've already released Jolokia 2.0. Please try it with 2.0 and see if there's still the issue. If there are no further activities here, I'd like to close it. Thank you.
