### ISSUE TITLE
Error accessing jolokia url

### ISSUE THREAD

**Issue by killerpapy** [jolokia/jolokia#472]
Hello, 

With my tomcat 9.0.41 with jdk8u275, jolokia war is not working.

The url https://server/jolokia give me a http 200 but i have an error message on the page :

{"stacktrace":"java.lang.IllegalArgumentException: No type with name 'error.jsp' exists\n\tat org.jolokia.util.RequestType.getTypeByName(RequestType.java:69)\n\tat org.jolokia.request.JmxRequestFactory.createGetRequest(JmxRequestFactory.java:94)\n\tat org.jolokia.http.HttpRequestHandler.handleGetRequest(HttpRequestHandler.java:79)\n\tat org.jolokia.http.AgentServlet$4.handleRequest(AgentServlet.java:470)\n\tat org.jolokia.http.AgentServlet.handleSecurely(AgentServlet.java:350)\n\tat org.jolokia.http.AgentServlet.handle(AgentServlet.java:321)\n\tat org.jolokia.http.AgentServlet.doGet(AgentServlet.java:277)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:626)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:733)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)\n\tat org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:461)\n\tat org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)\n\tat org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)\n\tat org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:398)\n\tat org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:257)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:179)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)\n\tat org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.lang.Thread.run(Thread.java:748)\n","error_type":"java.lang.IllegalArgumentException","error":"java.lang.IllegalArgumentException : No type with name 'error.jsp' exists","status":400}

**Comment by grgrzybek** [comment]
On Tomcat 9.0.80 and Jolokia 1.7.3-SNAPSHOT I'm getting (in browser):
```json
{"request":{"type":"version"},"value":{"agent":"1.7.2","protocol":"7.2","config":{"listenForHttpService":"true","maxCollectionSize":"0","authIgnoreCerts":"false","agentId":"192.168.0.221-82728-689f1dd-servlet","agentType":"servlet","policyLocation":"classpath:\/jolokia-access.xml","agentContext":"\/jolokia","mimeType":"text\/plain","discoveryEnabled":"false","streaming":"true","historyMaxEntries":"10","allowDnsReverseLookup":"true","maxObjects":"0","debug":"false","serializeException":"false","detectorOptions":"{}","dispatcherClasses":"org.jolokia.http.Jsr160ProxyNotEnabledByDefaultAnymoreDispatcher","multicastGroup":"239.192.48.84","maxDepth":"15","authMode":"basic","authMatch":"any","canonicalNaming":"true","allowErrorDetails":"true","realm":"jolokia","includeStackTrace":"true","multicastPort":"24884","useRestrictorService":"false","debugMaxEntries":"100"},"info":{"product":"tomcat","vendor":"Apache","version":"9.0.80"}},"timestamp":1695891489,"status":200}
```

and (in `curl`):
```
$ curl -s http://localhost:8080/jolokia | jq .
{
  "request": {
    "type": "version"
  },
  "value": {
    "agent": "1.7.2",
    "protocol": "7.2",
    "config": {
      "listenForHttpService": "true",
      "maxCollectionSize": "0",
      "authIgnoreCerts": "false",
      "agentId": "192.168.0.221-82728-689f1dd-servlet",
      "agentType": "servlet",
      "policyLocation": "classpath:/jolokia-access.xml",
      "agentContext": "/jolokia",
      "mimeType": "text/plain",
      "discoveryEnabled": "false",
      "streaming": "true",
      "historyMaxEntries": "10",
      "allowDnsReverseLookup": "true",
      "maxObjects": "0",
      "debug": "false",
      "serializeException": "false",
      "detectorOptions": "{}",
      "dispatcherClasses": "org.jolokia.http.Jsr160ProxyNotEnabledByDefaultAnymoreDispatcher",
      "multicastGroup": "239.192.48.84",
      "maxDepth": "15",
      "authMode": "basic",
      "authMatch": "any",
      "canonicalNaming": "true",
      "allowErrorDetails": "true",
      "realm": "jolokia",
      "includeStackTrace": "true",
      "multicastPort": "24884",
      "useRestrictorService": "false",
      "debugMaxEntries": "100"
    },
    "info": {
      "product": "tomcat",
      "vendor": "Apache",
      "version": "9.0.80"
    }
  },
  "timestamp": 1695891532,
  "status": 200
}
```

Same for Jolokia 2.0.0-SNAPSHOT on Tomcat 10.1.13:
```json
{"request":{"type":"version"},"value":{"agent":"2.0.0-SNAPSHOT","protocol":"7.2","details":{"agent_version":"2.0.0-SNAPSHOT","agent_id":"192.168.0.221-84998-5458683b-servlet","server_product":"tomcat","server_vendor":"Apache","server_version":"10.1.13","secured":false,"url":"http:\/\/192.168.0.221:8080\/jolokia"},"id":"192.168.0.221-84998-5458683b-servlet","config":{"agentId":"192.168.0.221-84998-5458683b-servlet","maxCollectionSize":"0","debug":"false","serializeException":"false","detectorOptions":"{}","dispatcherClasses":"org.jolokia.service.jsr160.Jsr160RequestHandler","maxDepth":"15","discoveryEnabled":"false","canonicalNaming":"true","historyMaxEntries":"10","includeStackTrace":"true","maxObjects":"0","debugMaxEntries":"100"},"info":{"proxy":{},"jmx":{}}},"status":200,"timestamp":1695891694}
```

```
$ curl -s http://localhost:8080/jolokia | jq .
{
  "request": {
    "type": "version"
  },
  "value": {
    "agent": "2.0.0-SNAPSHOT",
    "protocol": "7.2",
    "details": {
      "agent_version": "2.0.0-SNAPSHOT",
      "agent_id": "192.168.0.221-84998-5458683b-servlet",
      "server_product": "tomcat",
      "server_vendor": "Apache",
      "server_version": "10.1.13",
      "secured": false,
      "url": "http://192.168.0.221:8080/jolokia"
    },
    "id": "192.168.0.221-84998-5458683b-servlet",
    "config": {
      "agentId": "192.168.0.221-84998-5458683b-servlet",
      "maxCollectionSize": "0",
      "debug": "false",
      "serializeException": "false",
      "detectorOptions": "{}",
      "dispatcherClasses": "org.jolokia.service.jsr160.Jsr160RequestHandler",
      "maxDepth": "15",
      "discoveryEnabled": "false",
      "canonicalNaming": "true",
      "historyMaxEntries": "10",
      "includeStackTrace": "true",
      "maxObjects": "0",
      "debugMaxEntries": "100"
    },
    "info": {
      "proxy": {},
      "jmx": {}
    }
  },
  "status": 200,
  "timestamp": 1695891708
}
```

**Comment by grgrzybek** [comment]
If the problem is still there, please reopen.
