### ISSUE TITLE
How to get metrics on an endpoint

### ISSUE THREAD

**Issue by tusharsonawanes** [jolokia/jolokia#476]
Hello guys,

Using jmx-exporter, I can view the jvm metrics on an endpoint

Can the same be done using jolokia?

```java -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8080 -Dcom.sun.management.jmxremote.rmi.port=8080 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=<host-ip> -javaagent:jolokia.jar=port=8878,host=localhost -jar hello.jar```

Using the command above, when I browse the <host-ip>:8878/jolokia, no metrics can be seen

Using jconsole, we can see the graphs using pid or port 8080 on a remote machine

Is there any way through which we can get the jolokia jvm metrics on an endpoint?

**Comment by tadayosi** [comment]
I think you should invoke individual MBeans to get the metrics.

**Comment by rhuss** [comment]
You can use the [list](https://jolokia.org/reference/html/protocol.html#list) operation to list all available MBeans, or you can do a [wildcard read](https://jolokia.org/reference/html/protocol.html#read) to get jmx-export like bulk answer (but be careful with that, is that can easily become a really huge amount of data)

**Comment by grgrzybek** [comment]
Jolokia itself doesn't handle _metrics_. It _only_ provides "JMX Protocol Adaptor". JConsole while giving you access to mbeans, can also collect the values over a period of time. That's not the goal for Jolokia.

You could simply write a REST-client based application to collect some values using Jolokia, but aggregate/timeline them on your own.
