### ISSUE TITLE
Force jolokia-spring into default spring server

### ISSUE THREAD

**Issue by WoodenAndrew** [jolokia/jolokia#479]
I've come across an interesting issue when using jolokia-spring module. In my current project we're using jolokia 1.6.0 with spring integration. I've identified that spring integration uses sun.net.httpserver under the hood to spin up a secondary server which is dedicated to using jolokia. During java 8 days that worked fine, but sometimes after upgrading to java 11 this server would end up in SSL authentication loop which causes the memory thrashing like crazy. An image below shows memory graph before starting jolokia HTTP server and after.
![image](https://user-images.githubusercontent.com/72132647/136918995-3b986533-dfdc-444f-ab4d-bfa3ae143b76.png)
I've identified that most of these allocations are `java.nio.ByteBuffer[]` objects created by jolokia thread
![image](https://user-images.githubusercontent.com/72132647/136919661-6d47b77f-27cd-444a-960f-b4b6020e713f.png)

Question stands, how do I force jolokia into regular spring server (be it jetty, tomcat, or what ever) instead of letting jolokia to spawn its own?

Sadly, I am not in position to upload these flight recordings in public (nor send them privately).

**Comment by grgrzybek** [comment]
Hmm, I could simply run the JVM agent in non-ssl mode and it worked fine.

Also, for Jolokia 2 there are new options of running Jolokia - not only using JDK's own http server, but also with Spring Boot web starter and actuator feature.

**Comment by grgrzybek** [comment]
@WoodenAndrew, please check out [Jolokia Spring support](https://jolokia.org/reference/html/manual/spring.html) documentation.

You can configure Jolokia's `AgentServlet` using Spring's `org.springframework.boot.web.servlet.ServletRegistrationBean`. Also Spring Boot actuator can be configured with Jolokia endpoint.
