### ISSUE TITLE
XSD not found ->  https://jolokia.org/jolokia-spring/schema/config/jolokia-config.xsd  

### ISSUE THREAD

**Issue by marceloDanubioZalayeta** [jolokia/jolokia#493]
Hi, good day. Can you please take a look at the following.
I'm getting a 404 on subject xsd. I have maven dependencies jolokia-spring + jolokia-core + jolokia-client-java all of them in 1.7.1 version. I could not found the xsd on those dependencies
While trying to define Jolokia spring config as the doc shows:
![image](https://user-images.githubusercontent.com/88542735/149345176-d3f4c73e-af78-4487-9e1e-6d93595d581d.png)

![image](https://user-images.githubusercontent.com/88542735/149346121-35c817fa-a921-46a0-883e-414e1e9b4d83.png)

**Comment by apupier** [comment]
Hi,
a workaround should consist in replacing  http://jolokia.org/jolokia-spring/schema/config/jolokia-config.xsd by https://raw.githubusercontent.com/jolokia-org/jolokia-spring/master/src/main/resources/org/jolokia/support/spring/jolokia-config.xsd

**Comment by rhuss** [comment]
This should be fixed in the doc generation, not sure if this ever has worked

**Comment by grgrzybek** [comment]
Show soon (after 2.0 release) be available under:
* https://jolokia.org/jolokia-spring/schema/config/jolokia-config.xsd
* https://jolokia.org/jolokia-config.xsd
