### ISSUE TITLE
Jolokia agent not working  with an RMI-Server

### ISSUE THREAD

**Issue by anasoid** [jolokia/jolokia#494]
I try to use jolokia 1.7.1 agent with Jmeter, but not work with jmeter in server mode, but work fine if jmeter is not in server mode

![image](https://user-images.githubusercontent.com/10306838/152513074-e9dfc95a-7123-426d-871d-4be7f08928de.png)

**Step to reproduce :** 
Download jmeter , and jolokia and configure correctly jolokia.properties
Execute:

##NOT WORK##
$: export JVM_ARGS="-javaagent:../jolokia/jolokia-jvm-1.7.1.jar=config=../jolokia/jolokia.properties"
$: ./jmeter -n -s -Jserver.rmi.ssl.disable=true -Djava.rmi.server.hostname=192.168.11.200
Even we see message from jolokia (Jolokia: Agent started with URL ....) it doesn't work.

##WORK##
Execute jmeter in not server mode
$: ./jmeter -Jserver.rmi.ssl.disable=true -Djava.rmi.server.hostname=192.168.11.200

Jolokia work fine

I found similar problem on 

https://stackoverflow.com/questions/45730353/using-jolokia-agent-with-an-rmi-server

**Comment by grgrzybek** [comment]
Hmm, Jolokia's `org.jolokia.jvmagent.CleanupThread` thread stops Jolokia if there are no active non-daemon threads. When debugging, for a while I can access Jolokia Agent within JMeter run with `-n` option, but then I see a shutdown.

The non-daemon threads are:
```
$ jstack -l 21479 | grep tid | grep -v daemon
"RMI Reaper" #26 prio=5 os_prio=0 cpu=0,11ms elapsed=474,42s tid=0x00007f7f9d3c9800 nid=0x544f in Object.wait()  [0x00007f7f74bfe000]
"DestroyJavaVM" #29 prio=5 os_prio=0 cpu=777,50ms elapsed=474,39s tid=0x00007f7f9c028000 nid=0x53e8 waiting on condition  [0x0000000000000000]
"VM Thread" os_prio=0 cpu=56,07ms elapsed=492,46s tid=0x00007f7f9c44b800 nid=0x53ee runnable  
"GC Thread#0" os_prio=0 cpu=12,82ms elapsed=492,48s tid=0x00007f7f9c03d800 nid=0x53e9 runnable  
"GC Thread#1" os_prio=0 cpu=10,04ms elapsed=474,79s tid=0x00007f7f60049800 nid=0x543b runnable  
"GC Thread#2" os_prio=0 cpu=11,09ms elapsed=474,79s tid=0x00007f7f6004b000 nid=0x543c runnable  
"GC Thread#3" os_prio=0 cpu=10,83ms elapsed=474,79s tid=0x00007f7f6004c800 nid=0x543d runnable  
"GC Thread#4" os_prio=0 cpu=11,28ms elapsed=474,79s tid=0x00007f7f6004e000 nid=0x543e runnable  
"GC Thread#5" os_prio=0 cpu=10,66ms elapsed=474,79s tid=0x00007f7f6004f800 nid=0x543f runnable  
"GC Thread#6" os_prio=0 cpu=11,04ms elapsed=474,79s tid=0x00007f7f60051000 nid=0x5440 runnable  
"GC Thread#7" os_prio=0 cpu=11,18ms elapsed=474,79s tid=0x00007f7f60052800 nid=0x5441 runnable  
"GC Thread#8" os_prio=0 cpu=11,34ms elapsed=474,79s tid=0x00007f7f60054000 nid=0x5442 runnable  
"GC Thread#9" os_prio=0 cpu=10,79ms elapsed=474,79s tid=0x00007f7f60055800 nid=0x5443 runnable  
"G1 Main Marker" os_prio=0 cpu=0,41ms elapsed=492,48s tid=0x00007f7f9c059800 nid=0x53ea runnable  
"G1 Conc#0" os_prio=0 cpu=7,51ms elapsed=492,48s tid=0x00007f7f9c05b800 nid=0x53eb runnable  
"G1 Conc#1" os_prio=0 cpu=7,55ms elapsed=474,61s tid=0x00007f7f78001000 nid=0x5446 runnable  
"G1 Conc#2" os_prio=0 cpu=7,19ms elapsed=474,61s tid=0x00007f7f78002800 nid=0x5447 runnable  
"G1 Refine#0" os_prio=0 cpu=1,49ms elapsed=492,47s tid=0x00007f7f9c3b3000 nid=0x53ec runnable  
"G1 Refine#1" os_prio=0 cpu=0,55ms elapsed=474,79s tid=0x00007f7f6c001000 nid=0x5444 runnable  
"G1 Refine#2" os_prio=0 cpu=0,23ms elapsed=474,79s tid=0x00007f7ea8001000 nid=0x5445 runnable  
"G1 Young RemSet Sampling" os_prio=0 cpu=94,33ms elapsed=492,47s tid=0x00007f7f9c3b4800 nid=0x53ed runnable  
"VM Periodic Task Thread" os_prio=0 cpu=265,42ms elapsed=490,25s tid=0x00007f7f9c6e6000 nid=0x540b waiting on condition  
```

so Jolokia is stopped.

**Comment by grgrzybek** [comment]
Actually this was related to #399. `CleanupThread` was shutting down Jolokia when there were no more active non-daemon threads. And this was exactly the case when `./jmeter` was run with `-n` option.
