### ISSUE TITLE
Support java.util.Set type for JMX Adapter

### ISSUE THREAD

**Issue by apupier** [jolokia/jolokia#520]
It would be convenient to support Set type for JMX Adapter.

Currently, I'm hitting this kind of error:
```
Exception in thread "Camel DAP - Check Suspended node" java.lang.ClassCastException: class org.json.simple.JSONArray cannot be cast to class java.util.Set (org.json.simple.JSONArray is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @6576fe71; java.util.Set is in module java.base of loader 'bootstrap')
	at jdk.proxy2/jdk.proxy2.$Proxy25.suspendedBreakpointNodeIds(Unknown Source)
	at com.github.cameltooling.dap.internal.BacklogDebuggerConnectionManager.checkSuspendedBreakpoints(BacklogDebuggerConnectionManager.java:177)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by rhuss** [comment]
@skarsaune do you have an idea what would be needed to support `java.util.Set` ?

**Comment by skarsaune** [comment]
Interesting! 

Firstly, could you share the JMX information of the attribute/operation from either hawtio or a JMX browser ? (I'm interested in the meta information and signature). 

Then I guess there are several ways to look at this. `java.util.Set` is a bit peculiar, it is a subset of `java.util.Collection` it serves as a marker of semantics, but does not really provide anything that `java.util.Collection` does not. So if the code could rely on `java.util.Collection` that would solve the problem.

But if it is not possible to change the code and we want to support sets the JMX adapter, I guess we would.
1. With support of #505 allow clients to specify a type to represent a given implementation of `java.util.Set` (as Set is an interface we really need to specify what type)
2. Then the ToOpenTypeConverter would have to pick up that mapping and copy the values from the `JSONArray` into the specified Set implementation

**Comment by apupier** [comment]
![image](https://user-images.githubusercontent.com/1105127/199680840-0fa63b3b-6b91-4d04-8d56-4be212e6b220.png)

**Comment by apupier** [comment]
Before JSR-160 in Jolokia, for Jboss Tools, we were using this kind of code to do the conversion:

https://github.com/jbosstools/jbosstools-server/blob/55fbe48c139c08340d39cf25595e2d6b9fabd291/jmx/plugins/org.jboss.tools.jmx.jolokia/src/org/jboss/tools/jmx/jolokia/internal/connection/JolokiaJavaTypeConverter.java#L65

```	protected Object getConvertedCollection(JSONArray jolokiaReturnedValue, String realType) {
		if(Set.class.getName().equals(realType) || HashSet.class.getName().equals(realType)) {
			return new HashSet<Object>(jolokiaReturnedValue);
		} else {
			return jolokiaReturnedValue;
		}
	}
```

I believe that when only Set, the interface, is specified, we can choose the implementation class that we want.

**Comment by skarsaune** [comment]
Thanks. Would you be able to point me in the direction of a test dependency and a simple snippet that I could use in order for such an MBean to be present. So that I can actually run it? Thanks

**Comment by skarsaune** [comment]
In case it is a lot of trouble, I guess I could just create an MBean with a Set return value. But I suppose there are structured objects also within the Set? Do you have an example output from running that method with an ordinary jsr-160 JMX connection?

**Comment by apupier** [comment]
> Would you be able to point me in the direction of a test dependency and a simple snippet

trying to have a test to reproduce the issue for the last days and failing so far... :-(

> In case it is a lot of trouble, I guess I could just create an MBean with a Set return value. But I suppose there are structured objects also within the Set?

It is a Set of String https://github.com/apache/camel/blob/2b06753d6bef79b52e09cd1b6270ec64458ad62a/core/camel-management-api/src/main/java/org/apache/camel/api/management/mbean/ManagedBacklogDebuggerMBean.java#L110

So the "easiest" for now that I can propose to observe the incriminated MBean with which I encounter the issue is to launch `mvn camel:debug` on this example https://github.com/apache/camel-examples/tree/camel-examples-3.19.0/examples/main

> Do you have an example output from running that method with an ordinary jsr-160 JMX connection?

not sure that it is an ordinary jsr-160 connection, but using jconsole, when there is an empty Set I got:
![image](https://user-images.githubusercontent.com/1105127/199773896-17e37044-cb4a-475c-bb9c-0281c64a1c09.png)
when there is a value in the Set, i got:
![image](https://user-images.githubusercontent.com/1105127/199774452-8be46af0-daaa-46ce-9c14-791e6020bfbb.png)

**Comment by skarsaune** [comment]
Never mind. I should certainly be able to return Set<String> from an MBean.

**Comment by skarsaune** [comment]
Hmmm, I have written a test with a Set<String> attribute on an example MBean. When I do jolokia list on the MBean though, I get "type=[Ljava.lang.String;" for that attribute. Hence on the client side I am unable to deduct that it should be a set. I guess I can try to take more control of the MBeanInfo of the bean to specify an open type of Set. However I fear that this requirement will then not that easily support Set out of the box. However with the option of clients to override types with #505, it could be tolerable. Will try some more.  @apupier : How do you infer the `realType` in the jboss example above?

**Comment by apupier** [comment]
To infer the real type, it is from this piece of code:

https://github.com/jbosstools/jbosstools-server/blob/55fbe48c139c08340d39cf25595e2d6b9fabd291/jmx/plugins/org.jboss.tools.jmx.jolokia/src/org/jboss/tools/jmx/jolokia/internal/connection/JolokiaMBeanServerConnection.java#L282-L302

the idea is:
* getting all [MBeanInfo from an ObjectName](https://github.com/jbosstools/jbosstools-server/blob/55fbe48c139c08340d39cf25595e2d6b9fabd291/jmx/plugins/org.jboss.tools.jmx.jolokia/src/org/jboss/tools/jmx/jolokia/internal/connection/JolokiaMBeanServerConnection.java#L284)
* retrieving all [MBeanOperationInfo](https://github.com/jbosstools/jbosstools-server/blob/55fbe48c139c08340d39cf25595e2d6b9fabd291/jmx/plugins/org.jboss.tools.jmx.jolokia/src/org/jboss/tools/jmx/jolokia/internal/connection/JolokiaMBeanServerConnection.java#L286)
* then [filtering by name of operation](https://github.com/jbosstools/jbosstools-server/blob/55fbe48c139c08340d39cf25595e2d6b9fabd291/jmx/plugins/org.jboss.tools.jmx.jolokia/src/org/jboss/tools/jmx/jolokia/internal/connection/JolokiaMBeanServerConnection.java#L287
* [filtering by number of parameters in the signature](https://github.com/jbosstools/jbosstools-server/blob/55fbe48c139c08340d39cf25595e2d6b9fabd291/jmx/plugins/org.jboss.tools.jmx.jolokia/src/org/jboss/tools/jmx/jolokia/internal/connection/JolokiaMBeanServerConnection.java#L288)
* [finally get the `returnType`](https://github.com/jbosstools/jbosstools-server/blob/55fbe48c139c08340d39cf25595e2d6b9fabd291/jmx/plugins/org.jboss.tools.jmx.jolokia/src/org/jboss/tools/jmx/jolokia/internal/connection/JolokiaMBeanServerConnection.java#L292).


In this implementation, it is missing the case of several Operation with same name, same number of parameters with different types. I think this last case can be left behind as first iteration, chances are low to encounter it and we can fallback to current behavior.

**Comment by skarsaune** [comment]
I have tried to return a Set as both attribute and operation return value (as in the example above), tried both Set<String> and Set of more complex types however I get ArrayType regardless. So I have been unable to reproduce this. I'd be happy to include similar support as you have in JBoss tools, but would like to test with a real world example. @apupier Do you have a simple way to reproduce the  Camel example above that you hooked up a JMX console to?

**Comment by skarsaune** [comment]
@apupier : If you have a way to test this, would you like to create a PR? The handling of JSONArray return values is here: https://github.com/rhuss/jolokia/blob/7c21842fb6c99fc6c7ddb0a8187c9540887129e4/client/jmx-adapter/src/main/java/org/jolokia/client/jmxadapter/ToOpenTypeConverter.java#L161

**Comment by skarsaune** [comment]
@apupier : Good news. I got some help on #538 and added support for Set there.

**Comment by apupier** [comment]
awesome and thank you!

And sorry for not helping, I'm completely sidetracked these months but I still have it in mind.
