### ISSUE TITLE
Jolokia Agent Tomcat 10

### ISSUE THREAD

**Issue by iam333** [jolokia/jolokia#533]
Hi! thanks in advance

I have jolokia in some tomcat server versions and now I would put it in tomcat 10 but I have seen that it is not compatible.it's true?
Is there a forecast when there will be a compatible version?

Thanks!

**Comment by agebhar1** [comment]
Hi

see https://github.com/rhuss/jolokia/pull/484 / https://github.com/rhuss/jolokia/pull/540

**Comment by rhuss** [comment]
Closing as duplicate, let's continue on the other issues.

**Comment by grgrzybek** [comment]
Closing as duplicate of #451.
