### ISSUE TITLE
Parsing of arrays of bytes

### ISSUE THREAD

**Issue by juan-mart-delb** [jolokia/jolokia#534]
Using Jolokia 1.6.1 together with WildFly 21.0.0, I receive the following error when trying to invoke MBean operations using a byte array as argument.

> [Ljava.lang.Byte; cannot be cast to class [B

I am sending the byte array as an array of integers (in a JSON object) where the values are in the range [-128,127]. This seems to be fine because the operation throws different errors if the provided argument is not an array, if its values are not integers, or if the integers are outside that range. 

**EDIT:** The same error is thrown if the operation is invoked using an empty array

**Comment by grgrzybek** [comment]
@juan-mart-delb I'd have to see full stack trace, because from the tests I performed, I see no problem...
A write request with:
```json
{
  "value": [ 42, -42 ]
}
```
works both on methods accepting `byte[]` and `java.lang.Byte[]`. Relevant converters are used...

**Comment by grgrzybek** [comment]
@juan-mart-delb any news on this one?
