### ISSUE TITLE
Missing release notes for 1.7.2

### ISSUE THREAD

**Issue by rovarga** [jolokia/jolokia#537]
There is a https://github.com/rhuss/jolokia/releases/tag/v1.7.2 but there is no https://jolokia.org/changes-report.html#a1.7.2 . This looks like a release process omission.

**Comment by rhuss** [comment]
Yeah, sorry. The site's regeneration broke with an obscure error (you can find the release changes still in https://github.com/rhuss/jolokia/blob/master/src/changes/changes.xml and I hope I can fix this issue asap. But not this week, I'm fully booked already.

**Comment by grgrzybek** [comment]
https://jolokia.org/changes-report.html#a1.7.2 is available on new site.
