### ISSUE TITLE
connection of tomcat to jolokia

### ISSUE THREAD

**Issue by Bhaskar916** [jolokia/jolokia#552]
how to connect from tomcat to jolokia and what all configuration should be made

**Comment by tadayosi** [comment]
@Bhaskar916 You can read this:
https://jolokia.org/reference/html/agents.html#agents-war

**Comment by grgrzybek** [comment]
If by "from Tomcat" you mean "from a WAR application running on Tomcat", the answer is - please use any HTTP client you like and send GET/POST requests according to https://jolokia.org/reference/html/protocol.html
