### ISSUE TITLE
Prepare Jolokia BOM

### ISSUE THREAD

**Issue by grgrzybek** [jolokia/jolokia#562]
The bom would contain only `org.jolokia` managed dependencies.

**Comment by tadayosi** [comment]
It might not be related to this issue, but for SBOM (Software Bill of Materials) GitHub provides a builtin feature to generate it automatically for a project:
https://github.blog/changelog/2023-03-28-generate-an-sbom-from-the-dependency-graph/
So we can utilise this for Jolokia project.

**Comment by grgrzybek** [comment]
The BOM is ready: https://github.com/jolokia/jolokia/blob/2.0/bom/pom.xml
