### ISSUE TITLE
Additional JSON optimization mode

### ISSUE THREAD

**Issue by grgrzybek** [jolokia/jolokia#564]
Jolokia being the fundamental part of https://github.com/hawtio/hawtio/ is roughly mapping Java objects from JMX beans into hashmaps translated into JSON.

Hawtio over time was presenting more and more complex graphs of objects, including Camel routes and ActiveMQ brokers/queues/topics. In particular, when presenting thousands of ActiveMQ queues, we've found that a lot of JSON data is duplicated across similar objects.
Hawtio did some internal optimization and moved identical fragments into kind of _shared pool_ and then hundreds and thousands of objects were simply referring (by unique ID) to the common part.

For Hawtio and ActiveMQ, in some scenario, it allowed us to trim the JSON size from ~40MB to ~300kB and processing time on browser side from ~1 minute to <2 seconds.

The original issue is: https://issues.redhat.com/browse/ENTESB-4055

This is JSON equivalent of (un)famous [SOAP Encoding](https://www.w3.org/TR/2000/NOTE-SOAP-20000508/#_Toc478383512)

**Comment by tadayosi** [comment]
Thanks!  FYI, this is how Hawtio implements the optimised Jolokia LIST operation:

https://github.com/hawtio/hawtio/blob/cbfc5bc9113e8cce2ffbe1522f163ce50f6aed48/hawtio-system/src/main/java/io/hawt/jmx/RBACRegistry.java#L84-L112

This optimisation should be done per domain (e.g. `org.apache.camel`, `org.apache.activemq`, etc.) but once implemented at Jolokia we can expand the supported list incrementally.
