### ISSUE TITLE
Split JavaScript client from the project and into a dedicated npm project

### ISSUE THREAD

**Issue by tadayosi** [jolokia/jolokia#567]
Right now we have the JS client library under the same project with the Java agents and clients:
https://github.com/jolokia/jolokia/tree/main/client/javascript

But since the JS client should have a different release/update cadence than the Java artifacts and also JS has a different tooling ecosystem from Java's such as nodejs, npm, yarn, and testing frameworks like jest/karma/jasmine/cypress, IMO it's easier to make it a dedicated github project as a npm package and release it through the public npm registry. I think V2 is the best time if we go the path.

Ideas to work on if we split the JS client to a different project:

- Modernise the project by converting it to TypeScript
- Rewrite tests with popular testing frameworks such as Jest and Cypress
- Release it through `npm publish` to https://www.npmjs.com/ so that the client JS app can use it just by `npm i jolokia`
- Stop depending on jQuery and use the builtin Fetch API https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API so that the client app doesn't need to bother depending on jQuery for just using the Jolokia JS client

**Comment by rhuss** [comment]
Now that we have moved over to our own GitHub organisation I think that makes totally sense, not only for the JavaScript client library but also for other client libraries like Perl (jmx4perl), Python (e.g. https://github.com/wbrefvem/python-jolokia) or even the Java client library (but this needs to be discussed whether it wouldn't be better to keep the Java client library in the main repo).

I would also love to settle on a naming convention for the repository names for client libraries, like

* `jolokia/jolokia-client-javascript` (to reflect jolokia also in the checked-out directory name)
* `jolokia/client-javascript` (to have a shorter name, however the name only makes sense in the context of the GitHub orga then)

I think its also okay to switch the build tooling to `npm`, however, I would also love to publish the client as a webjar (https://www.webjars.org/) to make it easily embeddable in Java web backends.. Though I'm not sure if webjars are still a thing (i.e are actively maintained and propagated)

**Comment by tadayosi** [comment]
Thanks @rhuss for your comment! +1 for moving other client libraries as well, especially jmx4perl is a good candidate to move to the hawtio org if you'd like. For the Java client, I don't have a strong opinion about moving it. For the time being, we can perhaps keep it in the same Java project with the agents but I'm not also against moving it to a separate project all at once.

For the naming convention, personally +1 to `jolokia/client-javascript` as it's the same with the `kubernetes/kubernetes` and `kubernetes/client-go` naming convention, but again I don't have a strong opinion about it as well.

For webjars, for sure we should keep supporting the client distribution with it. If I'm not mistaken, once we release the client as a npm package to the public repository, it should be automatically available through webjars by:
```
<dependency>
    <groupId>org.webjars.npm</groupId>
    <artifactId>jolokia.js</artifactId>
    <version>2.0.0</version>
</dependency>
```
unless you want to publish it under `org.webjars` group id instead of `org.webjars.npm`.

**Comment by tadayosi** [comment]
One more idea I forgot to add to the original description:

- Stop depending on jQuery and use the builtin Fetch API https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API so that the client app doesn't need to bother depending on jQuery for just using the Jolokia JS client.

I'm updating the original description with it.

**Comment by rhuss** [comment]
I also think that `jolokia/client-javascript` is better since `jolokia/jolokia-client-javascript` would collide a bit with `jolokia/jolokia`, so +1 to use the shorter name.

**Comment by grgrzybek** [comment]
(One response at a time)

About naming artifacts/module directories. For #557 I've prepared a table of Maven artifact IDs and _all_ start with `jolokia-*`, so I'd keep it as is.

1. it was always like this
2. when using things like `mvn dependency:copy-dependencies` or putting the jars in one directory in any other way, we simply loose groupIds, so jar like `client-java-2.0.0.jar` doesn't looks like Jolokia ;)

For 2.0 (but also for 1.x), directory names are properly nested, so a Maven module called (its artifact ID) `jolokia-service-notif-sse` is contained in a directory called `service/notif/sse` (https://github.com/jolokia/jolokia/tree/2.0/service/notif/sse) and I'd also keep it as is.

**Comment by grgrzybek** [comment]
About jQuery removal.

jolokia.js uses these 5 functions from jQuery
* `$.ajax()`
* `$.each()`
* `$.extend()`
* `$.isArray()`
* `$.parseJSON()`

jolokia-cubism.js doesn't use jQuery

jolokia-simple.js uses these functions:
* `$.extend()`
* `$.isArray()`
* `$.isPlainObject()`
* `$.map()`

So in my opinion, if @tadayosi can reimplement  `$.ajax()` (other are trivial I believe) using fetch API, it'd be great and I'd be happy to not force users to use jQuery (or simply let them use any version without worrying about Jolokia).

**Comment by grgrzybek** [comment]
About moving jolokia.js to npm registry and package.

I could (not pushed change) create yarn workspace integrated with Maven structure.

Top level (`client/javascript`) package.json is:
```json
{
  "name": "jolokia",
  "private": true,
  "scripts": {
    "test": "yarn workspace jolokia-tests test"
  },
  "workspaces": [
    "src/test/javascript"
  ],
  "packageManager": "yarn@3.6.1"
}
```

`client/javascript/src/test/javascript/package.json` is:
```json
{
  "name": "jolokia-tests",
  "version": "2.0.0",
  "scripts": {
    "test": "jest --verbose"
  },
  "license": "Apache-2.0",
  "devDependencies": {
    "jest": "^29.6.2",
    "jest-environment-jsdom": "^29.6.2",
    "jquery": "^3.7.0"
  },
  "packageManager": "yarn@3.6.1"
}
```

and `client/javascript/src/test/javascript/hello-jolokia.test.js` is:
```javascript
/**
 * https://jestjs.io/docs/configuration#testenvironment-string
 * @jest-environment jsdom
 */

window.jQuery = require("jquery")
eval(require('fs').readFileSync("../../main/javascript/jolokia.js").toString());

let j = new Jolokia("/jolokia");

test('Jolokia test', () => {
    expect(j).not.toBeUndefined();
})
```

And the test works with top level `npm test`:
```
$ pwd
/home/ggrzybek/sources/github.com/jolokia/jolokia/client/javascript

$ npm test

> test
> yarn workspace jolokia-tests test

yarn workspace v1.22.19
yarn run v1.22.19
$ jest --verbose
 PASS  ./hello.test.js
  ✓ Hello test (16 ms)

 PASS  ./hello-jolokia.test.js
  ✓ Jolokia test (16 ms)

Test Suites: 2 passed, 2 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        2.307 s
Ran all test suites.
Done in 3.84s.
Done in 4.45s.
```

Then (I don't know about webjars) we could simply keep jolokia-client-javascript jar, but it'd fetch (frontend-maven-plugin?) jolokia.js from npm and package it for Java users.

WDYT?

**Comment by grgrzybek** [comment]
About TypeScript.

I'm neutral here - `jolokia.js` is well written IMO, but we surely can use TS if needed.

**Comment by tadayosi** [comment]
> (One response at a time)
> 
> About naming artifacts/module directories. For #557 I've prepared a table of Maven artifact IDs and _all_ start with `jolokia-*`, so I'd keep it as is.
> 
> 1. it was always like this
> 2. when using things like `mvn dependency:copy-dependencies` or putting the jars in one directory in any other way, we simply loose groupIds, so jar like `client-java-2.0.0.jar` doesn't looks like Jolokia ;)
> 
> For 2.0 (but also for 1.x), directory names are properly nested, so a Maven module called (its artifact ID) `jolokia-service-notif-sse` is contained in a directory called `service/notif/sse` (https://github.com/jolokia/jolokia/tree/2.0/service/notif/sse) and I'd also keep it as is.

That sounds like a strong point to follow the `jolokia/jolokia-client-javascript` naming option. I'm fine with keeping this existing naming convention then.

**Comment by tadayosi** [comment]
> About moving jolokia.js to npm registry and package.
> 
> I could (not pushed change) create yarn workspace integrated with Maven structure.
> 
> Top level (`client/javascript`) package.json is:
> 
> ```json
> {
>   "name": "jolokia",
>   "private": true,
>   "scripts": {
>     "test": "yarn workspace jolokia-tests test"
>   },
>   "workspaces": [
>     "src/test/javascript"
>   ],
>   "packageManager": "yarn@3.6.1"
> }
> ```
> 
> `client/javascript/src/test/javascript/package.json` is:
> 
> ```json
> {
>   "name": "jolokia-tests",
>   "version": "2.0.0",
>   "scripts": {
>     "test": "jest --verbose"
>   },
>   "license": "Apache-2.0",
>   "devDependencies": {
>     "jest": "^29.6.2",
>     "jest-environment-jsdom": "^29.6.2",
>     "jquery": "^3.7.0"
>   },
>   "packageManager": "yarn@3.6.1"
> }
> ```
> 
> and `client/javascript/src/test/javascript/hello-jolokia.test.js` is:
> 
> ```js
> /**
>  * https://jestjs.io/docs/configuration#testenvironment-string
>  * @jest-environment jsdom
>  */
> 
> window.jQuery = require("jquery")
> eval(require('fs').readFileSync("../../main/javascript/jolokia.js").toString());
> 
> let j = new Jolokia("/jolokia");
> 
> test('Jolokia test', () => {
>     expect(j).not.toBeUndefined();
> })
> ```
> 
> And the test works with top level `npm test`:
> 
> ```
> $ pwd
> /home/ggrzybek/sources/github.com/jolokia/jolokia/client/javascript
> 
> $ npm test
> 
> > test
> > yarn workspace jolokia-tests test
> 
> yarn workspace v1.22.19
> yarn run v1.22.19
> $ jest --verbose
>  PASS  ./hello.test.js
>   ✓ Hello test (16 ms)
> 
>  PASS  ./hello-jolokia.test.js
>   ✓ Jolokia test (16 ms)
> 
> Test Suites: 2 passed, 2 total
> Tests:       2 passed, 2 total
> Snapshots:   0 total
> Time:        2.307 s
> Ran all test suites.
> Done in 3.84s.
> Done in 4.45s.
> ```
> 
> Then (I don't know about webjars) we could simply keep jolokia-client-javascript jar, but it'd fetch (frontend-maven-plugin?) jolokia.js from npm and package it for Java users.
> 
> WDYT?

I'm also fine if we want to keep the JS client in the same project. I think the whole point of having it in the same project is that it's easy and consistent to release the jars and npm package under the same version and maven coordinates. As Roland suggested, there are other Jolokia clients (Perl, Python, etc.) and we still need to consider what to do with them, but for JS we'll then treat it as a special client that's bundled with the Jolokia agents.

Talking about the specifics of how to change the `client/javascript` project to a npm project, firstly we need to think if we should use yarn or npm. I'd prefer to be conservative with Jolokia and choose npm over yarn. At least, using yarn berry (v3) is a bit too early for the project so better to use the classic (v1) if we want to use yarn.

Secondly, I don't think we need to use yarn/npm workspace for the js client, as it's a single package and can accommodate both main and test code in a single one. I'd follow the convention of npm project where the main and test sources are co-located under `src/` directly, instead of `src/main` and `src/test` which is rather the manner of Java/Maven project.

**Comment by tadayosi** [comment]
> About TypeScript.
> 
> I'm neutral here - `jolokia.js` is well written IMO, but we surely can use TS if needed.

The benefits of converting it to TS are as follows:

- It can provide the type definitions (`.d.ts`) in a straightforward and consistent way
- We can think of types upfront
- Statically typed code should be easier for the Java programmers to contribute :wink: 
- No more IIFE magic code :wink: 

Let me try to convert `client/javascript` to TS on 2.0 branch.

**Comment by grgrzybek** [comment]
Thanks @tadayosi for comments. @rhuss so let's try converting [client/javascript](https://github.com/jolokia/jolokia/tree/2.0/client/javascript) to proper, conservative, non-workspace yarn project - with or without TS :)
Then the surrounding Maven module could pick up the jolokia.js and just maven-assemble it. WDYT?

**Comment by rhuss** [comment]
Tbh, I would prefer to keep as non-Typescript first, but provide the Typescript types in addition to make it easier to consume it in Typescript-based projects. I think it's already quite idiomatic Javascript (aka best practices) and I'm not sure how Javascript looks like that passed the Typescript compiler. It should be straight forward to include and examine jolokia.js for non-types script based projects that are consuming Jolokia. 

One of the main design goals was to have as less dependencies as possible (jquery was a compromise), so adding an extra level of abstraction might not be the best move.

But I'm open to be convinced if the transpiled Javascript is easy to consume and understand directly, and is not substantially larger than the original jolokia.js

**Comment by grgrzybek** [comment]
if the [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE) is the only _weird_ thing (though indeed - it's the best practice), then maybe keeping Javascript is better idea ;)

**Comment by tadayosi** [comment]
OK, then let's keep maintaining the current JS code as primary source and write type definitions manually on top of that. I wouldn't like to force pushing TypeScript when there are someones who find the current JS implementation useful for some reasons. There is already a type definitions file used in Hawtio, so it's not difficult to add.
https://github.com/hawtio/jolokia.js/blob/main/index.d.ts

I think the current TypeScript compilers are smart enough that they generate clean enough JS code (unless you minify it), so whenever we feel confident in TypeScript we could then return to it and consider converting it to TS again. Key points in adopting TypeScript are:

- It can hide the differences among JS versions, e.g. `ES5`, `ES6`/`ES2015`, `ES2016`, ..., `ESNext`, etc. and we can let TS compilers to apply the best practices on how to transpile TS to a specific version of JS
- Instead, if we choose to maintain JS code directly, we'd then need to be conscious about which minimum version of JS we should support (I expand it below).
- If we only add "devDependencies" to the project and are careful not to add any "dependencies", the "devDependencies" are used only at build time (like testing frameworks). The generated JS should be free from any runtime dependencies and can be used just as a pure independent JS file as it is.

My requirements for the JS client are:
- Should be able to install it with `npm i` or `yarn add` from the NPM registry
- Should support the common module importing methods: CommonJS, AMD(?), ES Modules

So, I think now it's important to discuss which minimum version of JS we'd like to support. Sensible options should be:

- **ES5** -- The start of modern JS. We can only use `var` and `function(...) {}` definitions. Still worth considering enabling `use strict` option to keep away from legacy JS pitfalls.
- **ES6/ES2015** -- We can use `const` and `let`, as well as arrow functions `(...) => {}`. We can also define `class`, which mean we can move away from IIFE from there. I'd prefer this version as minimum, as `const` and `let` are most useful among others as there are many pitfalls in `var`. Most browsers and Node.js should support ES6 already.
- **ES2016 or newer** -- More useful modern APIs.

> One of the main design goals was to have as less dependencies as possible (jquery was a compromise), so adding an extra level of abstraction might not be the best move.

In the light of this, we can also consider dropping JSON2 dependency by clearly stating that we support ES5 and newer (meaning we can always use `JSON.stringify()`).

@rhuss @grgrzybek WDYT?

**Comment by tadayosi** [comment]
> Should support the common module importing methods: CommonJS, AMD(?), ES Modules

Also, I'd like to discuss if we really want to keep supporting AMD (RequireJS)?  I don't see people use AMD these days.

**Comment by grgrzybek** [comment]
Thanks for great summary!
I didn't hear much about AMD modules recently and I think **ES6/ES2015** would be a great base (`const`/`let`).

And `package.json` withoud `dependencies` would be nice too ;)

**Comment by rhuss** [comment]
I have no strong opinions, except maybe that I always tried to support the oldest possible version e. g. for Java (even Java 6 is theoretically still supported), since I know many users that are stuck to legacy systems (enterprise users typically). I have no insights with the situation on JavaScript, I think the most browser are already beyond ES5 (though not sure), but I might wonder whether there are as many legacy node users as there are Java users. 

I think the question also it, what our future plans for the JavaScript client. Is it only about little feature and we can workaround the lack of modern language directives ? Or are there plans to expand jolokia.js considerably so that future work on Jolokia can be made easier with better language support ? Of course, if the usage of ES5 would prevent the usage of jolokia.js in more modern versions of JavaScript then I would be first to upgrade. But as long as it is possible to support older versions with a reasonable amount of effort (ideally: none :), then we should do this.

**Comment by rhuss** [comment]
Sorry, it's really about the users, not so much about us :) (btw, I have still a version of Jolokia that runs on Java 1.4, with a decent subset of features of the current Jolokia :-P

**Comment by grgrzybek** [comment]
Something not related directly to Javascript, but generally about 2.0.

While 1.x still supports (and I ensured that with ff4f020a994ac94944d0caf4e5d39cb424e50eb8) JDK6, for 2.0, which is going to support both Servlet API 4 and Servlet API 5+ (`jakarta.servlet`), I think it'd be wise/realistic to switch base JDK from JDK6 to JDK11. (please correct me if I'm too bold here).

So, assuming we go to JDK11+, with JavaScript we can safely go to JS standard from 2015+.

**Comment by rhuss** [comment]
Yes, that is definitely fine for me. I think the idea is, that Jolokia 1.x is now there for everything below Java 11, and Jolokia 2.x for Java 11 & Jakarta EE.

Saying that, I think it's ok to make the same cut for the JavaScript client, so happy to move on with ES6 ...

**Comment by grgrzybek** [comment]
Especially because I don't think it'd be a huge burden to support (and release) 1.x and 2.0 for some time in the future ;)

**Comment by tadayosi** [comment]
Thanks all for the discussion.

> I might wonder whether there are as many legacy node users as there are Java users.

I suspect not so, as Node.js evolves very fast and currently the only LTS is Node 18! (Node 16 has just EOL'ed a few days ago.)
https://github.com/nodejs/release#release-schedule
And most ES6 features have been supported with older Node versions for long time. https://node.green/#ES2015
But I understand that choosing conservatively is one good strategy to keep a project stable.

Btw, Oracle Java 11 support will end this month, so opensource communities will target to Java 17 LTS as their base soon :-)

> I think the question also it, what our future plans for the JavaScript client.

This is a very important point. Looking at the code change history, the JS client hasn't been changed so much for long time. I think it's because the Jolokia HTTP protocol has been very stable and backward compatible for long time. On the other hand, there are a few issues for the JS client that are not addressed for long time, partly because the JS client hasn't been updated (as I suspect).
https://github.com/jolokia/jolokia/issues?q=is%3Aissue+is%3Aopen+label%3A%22JavaScript+Client%22
Modernising the code base might open for more contributions and future enhancement requests. And some of them could be immediatedly resolved, such as #244 and #321.

I think the backward compatibility of the protocol and clients is a very good trait to maintain for Jolokia project. So why not keeping the backward compatibility, while opening up potential features and enhancements for the clients if they make sense?

> I think the idea is, that Jolokia 1.x is now there for everything below Java 11, and Jolokia 2.x for Java 11 & Jakarta EE.

+1. Yes, we can definitely keep Jolokia 1.x for a while for legacy users. I think it's good idea for us to look forward for Jolokia 2.x. And considering the backward compatibilty of Jolokia protocol, we might be able to keep using Jolokia 1.x clients against the 2.x agents for the users in a legacy environment.

**Comment by tadayosi** [comment]
So, to wrap up, here is my current plan for the JS client:

* As the first step, keep the JS client in ES5 (i.e. with `var` and IIFE) but apply [UMD](https://github.com/umdjs/umd) to convert it to a NPM package quickly
* Then, gradually convert it to ES6 (it could be done even after the initial 2.0 release)

**Comment by tadayosi** [comment]
The main part of the issue is done with #572 and #574. The remaining tasks are:

- [ ] Remove usages of jQuery from JS client as much as possible
- [ ] Convert the JS client to ES6 (should be done gradually over the future)

I'll create new issues for the subtasks and close this one.
