### ISSUE TITLE
Spring Boot 3 support -- any ETA?

### ISSUE THREAD

**Issue by mlesniak** [jolokia/jolokia#568]
Hello,

We're using Spring Admin to trigger JMX endpoints for some of our services. According to the [most recent documentation of Spring Admin](https://docs.spring-boot-admin.com/current/client.html), jolokia is not supporting SB3:

> ATTENTION: Spring Boot 3 does currently not support Jolokia, so this will not work with Spring Boot 3 based applications. You can still monitor Spring Boot 2 applications with Jolokia endpoint using a Spring Boot Admin 3 server.

Do you have any idea when SB3 will be supported or how difficult adding support is? Is this something that could be done by an outsider (more asking out of curiosity, not sure if this is even feasible)?

Best,
Michael

**Comment by grgrzybek** [comment]
Hello

Recently, the work on 2.0 branch has been restarted. The initial work on synchronization with recent (and not that recent) changes on main (1.x) branch is done.

Next stage (starting today) is about support for Servlets API 6 (javax → jakarta) which is the main and only item needed for Spring Boot 3 support. Then we'll see about the next steps. We can't promise any definite date, but expect more news soon ;)

**Comment by alvinlee001** [comment]
any updates?

**Comment by grgrzybek** [comment]
Hello

Please check:
* #555 
* #612
* perspilling/sba-example#1

With the perspilling/sba-example project, I helped to configure [Spring Boot Admin](http://docs.spring-boot-admin.com/current/getting-started.html) application with Jolokia 2.0.0-M4 and Spring Boot 3.

So - we're polishing stuff, changing documentation, updating deployment procedure, assembly content, etc. I was being distracted recently with my usual work, but the progress on Jolokia 2.0 is continuing.

For now you can check Jolokia 2.0.0-M4 available in Maven Central - in fact it'd be great if you could provide some feedback, so 2.0.0 release is really flawless.

**Comment by alvinlee001** [comment]
@grgrzybek i followed ur commit in my application and it works, hope u can also make ur code available in spring boot 3 soon... thanks for ur help =)

**Comment by grgrzybek** [comment]
spring-projects/spring-boot#37568 indicates that it should be quick on Spring Boot 3 side ;)

**Comment by wilkinsona** [comment]
https://github.com/spring-projects/spring-boot/issues/37568 shouldn't be interpreted that way. The work required may be quick, it may not. It depends on how much things have diverged since the support was removed in 3.0. More importantly, the changes then also have to make it into a release. With Spring Boot 3.2 now in the RC phase, the next release where Spring Boot could reinstate Jolokia support is 3.3 in May 2024.

**Comment by grgrzybek** [comment]
Thanks for your answer @wilkinsona.

While Jolokia 2 code is more or less stable, we're in the process of reviewing the documentation and in particular - the _Migration_ chapter.

I understand that Spring Boot 3.3 may be the first release that brings Jolokia back. Knowing that we could provide a SB autoconfigurer in Jolokia itself - in separate artifact that could be used in the meantime.

**Comment by wilkinsona** [comment]
> Knowing that we could provide a SB autoconfigurer in Jolokia itself - in separate artifact that could be used in the meantime

I think that's definitely worth considering, perhaps even for the longer term. It's a trade off between the benefit of having control over the schedule, feature set, and so on, versus the burden of having another module to maintain.

**Comment by grgrzybek** [comment]
With a202e3d1b23e7142220932a3b4e543c9c424ec55 there's an updated Jolokia module: `org.jolokia:jolokia-support-spring`.

It contains Spring Namespace handler (as in Jolokia 1), but also `/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports` file which effectively does the same as removed support for Jolokia 1 in Spring Boot 2 (see https://docs.spring.io/spring-boot/docs/2.7.18/reference/html/actuator.html#actuator.jmx.jolokia)
