### ISSUE TITLE
Remove usages of jQuery from JS client as much as possible

### ISSUE THREAD

**Issue by tadayosi** [jolokia/jolokia#575]
The JavaScript client should stop depending on jQuery and use the builtin Fetch API https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API, so that the client app doesn't need to bother depending on jQuery for just using the Jolokia JS client.

**Comment by grgrzybek** [comment]
@tadayosi please add very quick info about such changes to https://github.com/jolokia/jolokia/blob/2.0/src/site/asciidoc/migration.adoc - at some point (soon) I'll prepare proper "changes in 2.0" page.

**Comment by tadayosi** [comment]
What remain to be done:

- [ ] `$.extend`
- [ ] `$.ajax`

**Comment by tadayosi** [comment]
The current `jolokia.js` provides both sync and async modes, which is based on the `$.ajax` feature. I found it hard to completely replace it with Fetch API as it only supports async API. So forcing replacing `$.ajax` with Fetch API will bring destructive, backward incompatible changes to `jolokia.js`, which we should avoid.

It should be still preferable to have removed the rest of jQuery API usages from the JS client to minimise dependency to external libs.

Instead, I propose to create a yet another base JS client `jolokia-fetch.js` which is based on Fetch API and only supports async mode. Users who don't want to bring dependency to jQuery for their apps will be able to use this version of base JS client. `jolokia-simple.js` should be compatible with both versions, now that it itself doesn't have dependency to jquery.

@grgrzybek @rhuss FYI

**Comment by grgrzybek** [comment]
:+1:

**Comment by tadayosi** [comment]
I'll close this and follow it up with #580.
