### ISSUE TITLE
Convert the JavaScript client to ES6

### ISSUE THREAD

**Issue by tadayosi** [jolokia/jolokia#576]
Currently the JavaScript client is based on ES5 for maximum backward compatibility in many legacy environments, but we should look toward the future little by little. Let's discuss whether supporting ES5 as the baseline makes sense nowadays and consider converting the JS code to ES6/ES2015 and beyond if possible.

**Comment by grgrzybek** [comment]
@tadayosi please add very quick info about such changes to https://github.com/jolokia/jolokia/blob/2.0/src/site/asciidoc/migration.adoc - at some point (soon) I'll prepare proper "changes in 2.0" page.

**Comment by tadayosi** [comment]
Updated the doc: https://github.com/jolokia/jolokia/commit/f6bc68f164d9fbfae073cbc2bd14e48326e6284f

**Comment by grgrzybek** [comment]
When working on #580 I was (thanks @tadayosi for breaking my hesitation!) able to move to Typescript. Initially I only planned to use [eslint](https://eslint.org/) and [JSDoc](https://jsdoc.app/), but it was a bit messy. 

With TypeScript, Rollup and Jest I could create a nice environment where rollup created IIFE (UMD) based JS code and mjs files, while I could use jest and express.js to create real (extensible) tests.
