### ISSUE TITLE
Publish snapshot versions of Jolokia to Maven Central

### ISSUE THREAD

**Issue by tadayosi** [jolokia/jolokia#599]
We aren't yet ready for publishing a new milestone version of Jolokia 2.0 to Maven Central, while downstream projects are waiting for them to be available from Maven Central in order to start running CI workflows on their GitHub repos.

So, we should release snapshot versions of Jolokia 2.0 as part of our CI workflow.

**Comment by grgrzybek** [comment]
Is it still needed @tadayosi?

**Comment by tadayosi** [comment]
It's probably still nice to have, but really not necessary. Let's close it for now.

**Comment by grgrzybek** [comment]
I'm simply not sure if we can publish to https://repository.apache.org/snapshots/ through https://oss.sonatype.org/...
