### ISSUE TITLE
some metrics that generate by jolokia and send via telegraf to questdb drop because has dot in it

### ISSUE THREAD

**Issue by mehrdad2000** [jolokia/jolokia#610]
Is there any way to fix this issue with jolokia?

https://github.com/questdb/questdb/issues/3856

need to send metric with jolokia to questdb but some metrics has dot in their name and questdb drop them.

like these:
-PeakUsage.init
-CollectionUsage.max
-Usage.max

**Comment by grgrzybek** [comment]
> @grgrzybek Thanks, use rename feature of telegraf.

I ... don't quite understand...

**Comment by rhuss** [comment]
I think @mehrdad2000 refers to the ability to transform names in the telegraf import via configuration, so that you can get rid of forbidden characters during that process.

**Comment by grgrzybek** [comment]
So nothing that requires a change in Jolokia itself?

**Comment by mehrdad2000** [comment]
@rhuss exactly i rename fields before send to questdb with telegraf. and issue resolved.
