### ISSUE TITLE
(Logic of) LocalRequestDispatcher lost when upgrading to 2.0.0-M4

### ISSUE THREAD

**Issue by ohumbel** [jolokia/jolokia#612]
In https://github.com/jolokia/jolokia/pull/609 I was asked for feedback on how the migration to 2.0.0-M4 went. I spent quite a bit debugging the WildFly container, and here is what I found so far:

In the pre-2.0 world, the `org.jolokia.BackendManager` uses the `org.jolokia.backend.LocalRequestDispatcher` by default.
The LocalRequestDispatcher handles my JmxSearchRequest.

After upgrading to 2.2.0-M4, the `org.jolokia.server.core.backend.BackendManager` uses the `org.jolokia.server.core.backend.RequestDispatcherImpl`. This by default has exactly one RequestHandler: `org.jolokia.server.core.service.impl.VersionRequestHandler`. Therefore I get a 
`java.lang.IllegalStateException: Internal error: No request handler found for handling JmxSearchRequest[objectName = *:*]`.

For reference: [JmxAgentServlet.java.txt](https://github.com/jolokia/jolokia/files/13070830/JmxAgentServlet.java.txt) is my agent servlet.

Any advice how to get the _old request handling logic_ back would be greatly appreciated!

**Comment by ohumbel** [comment]
That helped a lot - thank you!

Previously, we only had the following dependency:
```
implementation "org.jolokia:jolokia-server-core:2.0.0-M4"
```

Now I added `jolokia-service-jmx`:
```
implementation "org.jolokia:jolokia-server-core:2.0.0-M4"
runtimeOnly "org.jolokia:jolokia-service-jmx:2.0.0-M4"
```
Having both .jars on the classpath , `RequestDispatcherImpl` now uses `org.jolokia.service.jmx.LocalRequestHandler` as well, and returns a result.

The client still does not render the result correctly. Now I really have to check the client code (what I did not yet).
I'll report back here.

**Comment by grgrzybek** [comment]
Looking forward for your feedback then.
What do you mean by "not render correctly" - is it about processing JSONs from Jolokia at client (browser) side?

**Comment by ohumbel** [comment]
> Looking forward for your feedback then. What do you mean by "not render correctly" - is it about processing JSONs from Jolokia at client (browser) side?

Yes, that was my suspicion: that the JSON sent to the client looks a bit different.

**But** - after successfully having created the result in `BackendManager` - a few lines later I get an `IllegalStateException` (feeling very stupid now):
```
java.lang.IllegalStateException: No service of type interface org.jolokia.server.core.service.serializer.Serializer found
	at deployment.BisonProcess.ear.CH.obj.webapp.war//org.jolokia.server.core.service.impl.JolokiaContextImpl.getMandatoryService(JolokiaContextImpl.java:82)
	at deployment.BisonProcess.ear.CH.obj.webapp.war//org.jolokia.server.core.backend.BackendManager.callRequestDispatcher(BackendManager.java:171)
	at deployment.BisonProcess.ear.CH.obj.webapp.war//org.jolokia.server.core.backend.BackendManager.handleRequest(BackendManager.java:93)
	at deployment.BisonProcess.ear.CH.obj.webapp.war//org.jolokia.server.core.http.HttpRequestHandler.executeRequest(HttpRequestHandler.java:198)
	at deployment.BisonProcess.ear.CH.obj.webapp.war//org.jolokia.server.core.http.HttpRequestHandler.handleGetRequest(HttpRequestHandler.java:81)
	at deployment.BisonProcess.ear.CH.obj.webapp.war//org.jolokia.server.core.http.AgentServlet$2.handleRequest(AgentServlet.java:515)
	at deployment.BisonProcess.ear.CH.obj.webapp.war//org.jolokia.server.core.http.AgentServlet.handleSecurely(AgentServlet.java:384)
	at deployment.BisonProcess.ear.CH.obj.webapp.war//org.jolokia.server.core.http.AgentServlet.handle(AgentServlet.java:335)
	at deployment.BisonProcess.ear.CH.obj.webapp.war//org.jolokia.server.core.http.AgentServlet.doGet(AgentServlet.java:288)
```

So my next question is: 
How do I register a serialization service? 
(`json-simple-1.1.1.jar` is on the classpath)

**Comment by grgrzybek** [comment]
BTW, I was just helping with similar problem - but with Spring Boot and Spring Boot Admin: perspilling/sba-example#1

`No service of type interface org.jolokia.server.core.service.serializer.Serializer` means you miss `org.jolokia:jolokia-service-serializer:2.0.0-M4` jar on your classpath.

**Comment by ohumbel** [comment]
OK, got it.
Will just try to add the last missing dependency of your [commit](https://github.com/perspilling/sba-example/pull/1/commits/ac2ae2a9d21ee8827f5b6d3c4841ceb4269e8e8b).

**Comment by ohumbel** [comment]
It works now - thank you very much!

If we should meet in person once, I definitely owe you a beer :+1:

**Comment by ohumbel** [comment]
Closing

**Comment by eolivelli** [comment]
I have the same problem:
"No service of type interface org.jolokia.server.core.service.serializer.Serializer"

and I have:
```
		<dependency>
			<groupId>org.jolokia</groupId>
			<artifactId>jolokia-server-core</artifactId>
			<version>${jolokia.version}</version>
		</dependency>
		<dependency>
			<groupId>org.jolokia</groupId>
			<artifactId>jolokia-service-jmx</artifactId>
			<version>${jolokia.version}</version>
		</dependency>
		<dependency>
			<groupId>org.jolokia</groupId>
			<artifactId>jolokia-service-serializer</artifactId>
			<version>${jolokia.version}</version>
		</dependency>
```

all good in unit tests, but when I launch my application it fails.
the main difference is that I have an "uber" jar with all the dependencies, is there any special file to add to the class path ? how is that service looked up ?

**Comment by grgrzybek** [comment]
> when I launch my application

you need to be more specific about how you run your application - are these 3 dependencies part of Maven project which uses Spring Boot? Is it a standalone (no framework) application?

If you want everything in one jar, you can use `org.jolokia:jolokia-agent-jvm` artifact with `javaagent` classifier, but your specific case may be different.

What's your classpath? How do you run your app?

**Comment by eolivelli** [comment]
This is my workaround:

```
 <groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-shade-plugin</artifactId>
....
<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/jolokia/services-default</resource>
</transformer>
```

**Comment by grgrzybek** [comment]
Exactly - that's what we do in Jolokia as well:
https://github.com/jolokia/jolokia/blob/969adb27d89be15e7cb83845c2576d5c3ef6ff8e/agent/jvm/pom.xml#L245-L259

**Comment by eolivelli** [comment]
I wonder if we could improve the documentation or the error message

**Comment by grgrzybek** [comment]
The _extension_ chapter is here: https://jolokia.org/reference/html/manual/extensions.html
Sure - there's no section about `org.apache.maven.plugins.shade.resource.AppendingTransformer`, but I think it's quite too low level and not Jolokia related (it's a Maven thing).

But feel free to contribute ;)
