### ISSUE TITLE
Wildcards not working to get all available MBeans

### ISSUE THREAD

**Issue by kb-elmo** [jolokia/jolokia#615]
I recently found some weird behaviour in Jolokia when being used with wildcards to get some metrics from the Scylla-JMX tool.

When trying to get some of the available metrics with wilcards I only get an "javax.management.InstanceNotFoundException" error.
However the metrics are there, are shown in the mbean list and I can get the values when specifying the entire mbean path without any wildcards.

For example:
`$ /jolokia/read/org.apache.cassandra.metrics:keyspace=system_schema,name=WriteTotalLatency,scope=types,type=ColumnFamily`
works and gives me a valid result with a value

`$ /jolokia/read/org.apache.cassandra.metrics:keyspace=system_schema,name=WriteTotalLatency,scope=types,type=*`
however results in an instanceNotFound Error which doesn't really make sense to me.

As said, the metric shows up in the metric list from the Jolokia agent
`$ /jolokia/list`
```json
"org.apache.cassandra.metrics": {
  "keyspace=system_schema,name=WriteTotalLatency,scope=types,type=ColumnFamily": {
    "attr": {
      "Count": {
        "rw": false,
        "type": "long",
        "desc": "Attribute exposed for management"
      }
    },
    "class": "org.apache.cassandra.metrics.MetricsRegistry$JmxCounter",
    "desc": "Information on the management interface of the MBean"
  }
}
```

This seems like a bug in the agent?
It should be able to find the mbean with a wildcard if it's in the list and can be accessed directly.

**Comment by grgrzybek** [comment]
I'll check soon - I don't remember whether `*` should translate into first found instance matching the pattern...

**Comment by tadayosi** [comment]
If it's an issue with Jolokia 1.x, we can put it aside until we release 2.0 GA.

**Comment by rhuss** [comment]
Wildcards are not working on the attribute value-level but only on the value level itself.

E.g. 

```
/jolokia/read/org.apache.cassandra.metrics:keyspace=system_schema,name=WriteTotalLatency,scope=types,type=*
```

does not work, while 

```
/jolokia/read/org.apache.cassandra.metrics:keyspace=system_schema,name=WriteTotalLatency,scope=types,*
```

should work as expected. The wildcards semantics are defined by JMX, see here for details https://docs.oracle.com/javase/1.5.0/docs/api/javax/management/ObjectName.html

I'm afraid, there is not much we can do from Jolokia side.

**Comment by tadayosi** [comment]
Then it sounds like a documentation issue. Maybe we should add a dedicated section for explaining the wildcards usages.

**Comment by grgrzybek** [comment]
> Then it sounds like a documentation issue. Maybe we should add a dedicated section for explaining the wildcards usages.

Definitely that's my plan - especially in relation to new URI constraints (GET Jolokia protocol) - see #573.

**Comment by kb-elmo** [comment]
> Wildcards are not working on the attribute value-level but only on the value level itself.
> 
> E.g.
> 
> ```
> /jolokia/read/org.apache.cassandra.metrics:keyspace=system_schema,name=WriteTotalLatency,scope=types,type=*
> ```
> 
> does not work, while
> 
> ```
> /jolokia/read/org.apache.cassandra.metrics:keyspace=system_schema,name=WriteTotalLatency,scope=types,*
> ```
> 
> should work as expected. The wildcards semantics are defined by JMX, see here for details https://docs.oracle.com/javase/1.5.0/docs/api/javax/management/ObjectName.html
> 
> I'm afraid, there is not much we can do from Jolokia side.

Sorry but...
This is not the case and the first notation is even used in the example for the Telegraf Jolokia config for Apache Cassandra.
See: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/cassandra/README.md

And both in fact work perfectly fine when used with Cassandra and some other metrics like those of the JVM itself.

```json
$ curl -s localhost:8778/jolokia/read/org.apache.cassandra.metrics:keyspace=system_schema,name=WriteTotalLatency,scope=types,type=* | jq
{
  "request": {
    "mbean": "org.apache.cassandra.metrics:keyspace=system_schema,name=WriteTotalLatency,scope=types,type=*",
    "type": "read"
  },
  "value": {
    "org.apache.cassandra.metrics:keyspace=system_schema,name=WriteTotalLatency,scope=types,type=Table": {
      "Count": 100
    }
  },
  "timestamp": 1701074816,
  "status": 200
}
```

However neither of those two notation types work seemingly random with some other JMX metrics which is what's confusing me here.
I did a bit more digging and found one interesting difference.

The metrics that do show up in the wildcard requests have an additional section in the mbean list.
```json
"op": {
  "objectName": {
    "args": [],
    "ret": "javax.management.ObjectName",
    "desc": "Operation exposed for management"
  }
}
```

This is missing in the mbean list on those metrics that do not work with any kind of wildcard search.
I have no idea what the "op" section is meant for or where it's coming from, but it seems that Jolokia is ignoring metrics in wildcard searches if this part is not present.

**Comment by kb-elmo** [comment]
When I use the search it finds the metrics without issues.

```json
$ curl -s "localhost:8778/jolokia/search/*:name=WriteTotalLatency,*" | jq
{
  "request": {
    "mbean": "*:name=WriteTotalLatency,*",
    "type": "search"
  },
  "value": [],
  "timestamp": 1701104681,
  "status": 200
}

It also works with other keys and returns a list of all metrics that are also found in the list response.
So that doesn't seem to be a problem.
```

**Comment by rhuss** [comment]
@kb-elmo I mean, can you try to search with a pattern in the value part like in `org.apache.cassandra.metrics:keyspace=system_schema,name=WriteTotalLatency,scope=types,type=*` ? And then also please try the `read` with a POST curl request (by sending the appropriate JSON structure representing the request)

**Comment by grgrzybek** [comment]
I've reviewed the escaping rules and I also believe there must be something on JVM/JMX side... Can you share more details about JDK you're using and what's exactly on your CLASSPATH? Can you share some sample project via GitHub?

**Comment by kb-elmo** [comment]
Sorry for not giving any updates in a while.

It indeed seems that this is caused by the "emulated" JVM that the Scylla-JMX tool uses.
I will close this here and ask the Scylla people for help instead.

Thanks for looking into it though! :smiley:
