### ISSUE TITLE
Errors with recent version of Felix framework (7.0.5) and Apache Felix Http service (4.2.18).

### ISSUE THREAD

**Issue by freyssin** [jolokia/jolokia#617]
Although I am not sure if the problem is Jolokia's responsibility, I would like to report this malfunction. It seems that the OSGi Jolokia bundle no longer installs with the latest versions of the Felix framework.

I have been using the Jolokia bundle with the Felix framework and Apache Felix Http Jetty for many years, and following the Felix update (7.0.5 for framework and 4.2.18 for Http service) I get the following error:

> ERROR: Bundle org.jolokia.osgi [64] Error starting file:./bundle/jolokia-osgi-1.7.2.jar (org.osgi.framework.BundleException: Unable to resolve org.jolokia.osgi [64](R 64.0): missing requirement [org.jolokia.osgi [64](R 64.0)] osgi.wiring.package; (&(osgi.wiring.package=org.osgi.service.log)(version>=1.0.0)(!(version>=2.0.0))) Unresolved requirements: [[org.jolokia.osgi [64](R 64.0)] osgi.wiring.package; (&(osgi.wiring.package=org.osgi.service.log)(version>=1.0.0)(!(version>=2.0.0)))])
> org.osgi.framework.BundleException: Unable to resolve org.jolokia.osgi [64](R 64.0): missing requirement [org.jolokia.osgi [64](R 64.0)] osgi.wiring.package; (&(osgi.wiring.package=org.osgi.service.log)(version>=1.0.0)(!(version>=2.0.0))) Unresolved requirements: [[org.jolokia.osgi [64](R 64.0)] osgi.wiring.package; (&(osgi.wiring.package=org.osgi.service.log)(version>=1.0.0)(!(version>=2.0.0)))]
>         at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4398)
>         at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
>         at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1566)
>         at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:297)
>         at java.base/java.lang.Thread.run(Thread.java:829)

I tried the latest version of Jolokia without any behavior improvement. I specify that I do not use the standard version of the bundle and not the "all-in-one bundle" version.

Thank you for this component.

**Comment by grgrzybek** [comment]
You need an implementation of `org.osgi.service.log` service. you can install Pax Logging bundles or Felix log for example.
