### ISSUE TITLE
package org.jolokia.service.discovery should be exported, to make it possible to use JolokiaDiscovery in an OSGi context

### ISSUE THREAD

**Issue by skarsaune** [jolokia/jolokia#673]
Package can be exported here: 
https://github.com/jolokia/jolokia/blob/9fc1b952607ad48737eacb3c9227ea67d8612917/service/discovery/pom.xml#L74

Result when trying to use JolokiaDiscovery from Java Mission Control:

[ERROR] /home/marska/Documents/dev/jmc/jmc/application/org.openjdk.jmc.jolokia/src/main/java/org/openjdk/jmc/jolokia/JolokiaDiscoveryListener.java:[43] 
[ERROR] 	import org.jolokia.service.discovery.JolokiaDiscovery;
[ERROR] 	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Access restriction: The type 'JolokiaDiscovery' is not API (restriction on classpath entry '/home/marska/.m2/repository/p2/osgi/bundle/org.jolokia.service.discovery/2.0.2/org.jolokia.service.discovery-2.0.2.jar')

**Comment by grgrzybek** [comment]
You're right. However _the_ way to use Jolokia 2 in OSGi is to use single `jolokia-agent-osgi` bundle which exports all the packages. See https://github.com/jolokia/jolokia/blob/main/agent/osgi/pom.xml#L185-L187

**Comment by skarsaune** [comment]
I see. Thanks. I was hoping to use discovery with minimal other dependencies, but that suggestion should solve my need for now.

**Comment by grgrzybek** [comment]
I admit that it was on purpose and out of little laziness - I assumed you need one bundle in OSGi with everything inside. Especially that you can't use jolokia-service-discovery on its own - you need the server-core too.

**Comment by grgrzybek** [comment]
There's no plan to prepare something like Karaf feature(s) with bundles inside. The way to use Jolokia 2 with OSGi is simply to use `org.jolokia:jolokia-agent-osgi` bundle.

If you believe there's a place for improvement, please reopen.
