### ISSUE TITLE
Load full certificate chain from pem (so Let's Encrypt certificates could be used)

### ISSUE THREAD

**Issue by shayelkin** [jolokia/jolokia#675]
When setting `serverCert`, only the first certificate would be loaded from that file, which, in the case of using an intermediate CA, would cause an incomplete (and hence, not trusted) chain to be presented to clients.

This is literally a 2-line fix, made the following PR, and would appreciate a review:
https://github.com/jolokia/jolokia/pull/674

**Comment by grgrzybek** [comment]
Fix: 58e97998a6e98425dac4c82a0d862471026c41d2

**Comment by grgrzybek** [comment]
I had to disable a test using ftp://ftp.redhat.com...
