### ISSUE TITLE
Move DNS jolokia.org to a more neutral account

### ISSUE THREAD

**Issue by rhuss** [jolokia/jolokia#684]
Currently, `jolokia.org` is still registered in my private name, but I think it would be nice to move to a more neutral location, like a Red Hat account.

wdyt ?

(I just paid it for the next year, so there is no time pressure)

**Comment by grgrzybek** [comment]
cc: @lhein

**Comment by rhuss** [comment]
I got the pointer by @lhein so that I know how to transfer. Thanks!
