### ISSUE TITLE
does jolokia support IBM IIB?

### ISSUE THREAD

**Issue by mehrdad2000** [jolokia/jolokia#709]
Hi
does jolokia support IBM IIB?
or i can use JVM agent?

Any idea?
Thanks

**Comment by grgrzybek** [comment]
IBM IIB? IBM® Integration Bus?
If it is a Java server that allows WAR deployments or allows to specify `-javaagent` startup option, Jolokia agent should work without problems.
There may be issues discovering MBeanServer (and/or IBM IIB specific MBeans if these are not registered into standard _Platform MBeanServer_) though.
Also if IIB uses `-Djavax.management.builder.initial` to configure some fancy MBeanServerBuilder, Jolokia may be prevented to use it correctly...

**Comment by mehrdad2000** [comment]
@grgrzybek need to know number of messages in message flow, does it support?

**Comment by grgrzybek** [comment]
If IBM Integration Bus is not a Java process, I'm afraid there's nothing Jolokia can do...
