### ISSUE TITLE
Improve Karaf support

### ISSUE THREAD

**Issue by rhuss** [jolokia/jolokia#73]
While Karaf works perfectly with the current agents (osgi, osgi-bundle, jvm), the support can be improved:
- Add a Jolokia Karaf feature
- Add a dedicated Karaf detector

**Comment by rhuss** [comment]
We should put this also into a new repo (like we want to do for spring-roo and Mule agent support). See #205 for details.

**Comment by tadayosi** [comment]
Current links referred to in @jstrachan's comment:
https://github.com/jboss-fuse/fabric8/blob/1.2.0.redhat-6-3-x/fabric/fabric8-karaf/src/main/resources/fabric-features.xml#L588-L592
https://github.com/jboss-fuse/fabric8/tree/1.2.0.redhat-6-3-x/fabric/fabric-jolokia

**Comment by tadayosi** [comment]
Is it sill relevant?  If not, then maybe we can close it. @grgrzybek @rhuss

**Comment by grgrzybek** [comment]
I don't think we need special Karaf `jolokia` feature. With Jolokia 2.0 it's just one bundle... And it's working well enough in OSGI ;).

@jstrachan do you feel like going for sentimental trip to OSGi land and verify the requirements? :)
