### ISSUE TITLE
Handling of origin/referer header fails behind a web server proxy

### ISSUE THREAD

**Issue by rfelgent** [jolokia/jolokia#731]
Hi,

I am running a Spring Boot 3.3.1 app with Hawtio 4.1.0 in a kuberntes cluster.
 
The url for accessing jolokia from "outside" is "https" based, e.g. "https://my-app.production.local/hawtio/jolokia" and the request fails with the exception message `Secure origin https://my-app.producation.local/hawtio/jolokia should not be processed over HTTP`.

The logic is part of org.jolokia.server.core.http.HttpRequestHandler#checkAccess

```
public void checkAccess(String pRequestScheme, String pHost, String pAddress, String pOrigin) {
        if (!jolokiaCtx.isRemoteAccessAllowed(pHost != null ? new String[] { pHost, pAddress } : new String[] { pAddress })) {
            throw new SecurityException("No access from client " + pAddress + " allowed");
        }
        if (!jolokiaCtx.isOriginAllowed(pOrigin, true)) {
            throw new SecurityException("Origin " + pOrigin + " is not allowed to call this agent");
        }

        // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin
        if ("http".equals(pRequestScheme) && pOrigin != null && !"null".equals(pOrigin)) {
            try {
                String originScheme = new URL(pOrigin).getProtocol();
                // Requests with HTTPS origin should not be responded over HTTP,
                // as it compromises data confidentiality and integrity.
                if ("https".equals(originScheme)) {
                    throw new SecurityException("Secure origin " + pOrigin + " should not be processed over HTTP");
                }
            } catch (MalformedURLException e) {
                // Ignore it, should be safe as origin is not https anyway
            }
        }
    }
```

Furthermore, I tried to de-activate the `<strict-checking/>` flag by providing a `jolokia-access.xml` with the following content:
```
<?xml version="1.0" encoding="utf-8"?>
<restrict>
  <cors>
    <allow-origin>*://*.production.local*</allow-origin>
    <allow-origin>*://localhost*</allow-origin>

    <!--
    <strict-checking/>
    -->
  </cors>
</restrict>
```

My 2 cents:

1) According to the documentation the security check for "referer" and "origin" header is skipped, if the `<strict-checking>/` is not provided, isn'it ? My assumption is based on the negation of 
```
If the option <strict-checking/> is given in this section, too, then the given patterns are not only used for CORS checking but also every request is checked on the server side whether the Origin: or Referer: header matches one of the given patterns. If neither Origin: nor Referer: is given and strict checking is enabled, then the access is denied. This useful for protecting against Cross-Site Request Forgery.
```

see https://jolokia.org/reference/html/manual/security.html#_cross_origin_resource_sharing_cors_restrictions

2) The code part in `HttpRequestHandler` does not honor the configuration `<strict-checking/>` flag. I would love to change that behavior in a way, that this security check can be enabled/disabled at will.

3) Am I missing something when running jolokia behind a web proxy ?

Best regards

**Comment by grgrzybek** [comment]
See also #621.

**Comment by grgrzybek** [comment]
@tadayosi this check was added in 5dc3b4b01a54710e46a1d73c8ad431f8b878d805 - do you think it's safe to handle such scenario where Jolokia runs behind proxy (nginx or k8s)?
It's quite common to have HTTPS proxy around non-HTTP endpoint and the client can send `Origin` header of the proxy, not the backend...

**Comment by tadayosi** [comment]
The point is that if HTTPS is used but in midstream the request is transfered over HTTP, confidentiality is never guaranteed. This countermeasure is advised by the security best practices. I don't think using nginx or k8s proxy resolves the confidentiality problem.

But if we think it's too restrictive, we may possibly provide a configuration option that disables the check at the user's own risk.

**Comment by rfelgent** [comment]
Hi @tadayosi and @grgrzybek ,

thank you guys for your feedback!

@grgrzybek , I am not sure whether your x-forward header issue can solve the "origin/referer" header problem behind a web proxy, because those "origin/referer" headers are not (explicitly) covered by the https://tools.ietf.org/html/rfc7239.  Therefore, a lot of tools/frameworks are lacking out-of-the box support to handle those "orgin/referer" header.

@tadayosi , you nailed my feature request/bug report by writing `But if we think it's too restrictive, we may possibly provide a configuration option that disables the check at the user's own risk.`

It would be nice to have such a configuration flag to enable/disable the check for "origin/referer" header. (feature request)
 
According to the documentation, I thought this is already be possible - but I was wrong or mis-understand the jolokia documentation regarding `<strict-checking/>` (bug report for unclear documentation ?!)


I'd like to make clear, that it took some time for me to find the cause for a "not working hawtio-springboot:4.1.0 with spring-boot:v3.3 setup" in our K8s environment. In the end, I created  custom web filter for removing the "origin/referer" header.


Should I provide a pull request for providing a configuration option regarding origin/referer header check ?

**Comment by grgrzybek** [comment]
I've added new option to `jolokia-access.xml` (and its XSD). If you don't change the default config, the behavior is the same - `Origin` header with `https` scheme is _not_ allowed via `http` protocol.

But if you use this:
```xml
<cors>
  <ignore-scheme/>
</cors>
```

then you're scenario will work. In the documentation I highlighted that this option may be needed behind TLS proxy.

**Comment by rfelgent** [comment]
Unbelievable @grgrzybek , I just finished my comment on that topic and 5 minutes later, you provided a MR for this feature flag. Thank you very much !

**Comment by grgrzybek** [comment]
Unbelievable² - I just finished _my_ comment and saw yours ;)

Clarifying `<strict-checking />` option - without strict checking, cors header verification happens only for _CORS preflight requests_ (http `OPTION` method). With strict checking, `Origin` header is also checked in normal `GET`, `POST` requests.

**Comment by grgrzybek** [comment]
And yes - #621 is actually not related.
