### ISSUE TITLE
Extend Jolokia Roo-Addon

### ISSUE THREAD

**Issue by rhuss** [jolokia/jolokia#75]
The Jolokia Roo-Addon (under `tools/roo-addon`) currently only add the WAR agent to a `web.xml` for Web projects. Now with the new Spring support in place this add-on can be extended:
- Allow the addition of `<jolokia:agent>` to the application context, along with all possible configuration options (or at least the most importan)
- Allow the addition of `@JsonMBean` to JMX exposed classes.
- Add a possibility to add the Jolokia MBeanServer to `<context:mbean-export>`

**Comment by rhuss** [comment]
Is anybody using the Roo Plugin ? 

Probably not, so I might consider to move it into an extra repo, the same way as the mule support is going to be  moved into an extra repo.

**Comment by grgrzybek** [comment]
Closing as out of date. Roo is deprecated in favor of Spring Boot.
