### ISSUE TITLE
<filter> in security policy not working

### ISSUE THREAD

**Issue by hailengc** [jolokia/jolokia#758]
According to the [documentation here](https://jolokia.org/reference/html/manual/security.html#_disable_listingsearching_of_selected_mbeans):  "`Using \<filter\> element we can filter out results of list and search operations (even if search parameters include such MBean names).`" . There is also a concrete example in the doc that shows how to use it.

However from my test, `<filter>` element is not working neither for `list` nor `search` operation. I looked into the source code and could not find any related logic that handles `<filter>` element from security policy.  I verified against both Jolokia 1.x and 2.x branch.

My questions are:
* Is it correct ( or a known issue) that `<filter>`  in security policy is not working?
* If it truly not working, would like to know if any plan on the roadmap to fix it?
* If it truly not working , could we take this section down from the official documentation to avoid confusion until we fix it?

**Comment by grgrzybek** [comment]
Which version are you using? This is fixed in https://github.com/jolokia/jolokia/commit/8362da648449881955648c9df9c3c263d059cca8 (since 2.1.0) and it's about adding:
```xml
<filter>
```

in `jolokia-access.xml` file (should be available on classpath or configured using `policyLocation` parameter).

**Comment by hailengc** [comment]
Thank you for the reply!
I tested on Jolokia 1.x and Jolokia 2.0.3 versions and that's why `<filter>` is not working.
Just a small suggestion on the documentation, would be nice to clearly state the exact version that supports it to avoid confusion.

**Comment by grgrzybek** [comment]
Thanks for suggestion - you're right, I should've mentioned this. I'll remember to indicate _since version_ correctly.

**Comment by grgrzybek** [comment]
Added a comment - will be available at Jolokia page and reference documentation soon.

**Comment by hailengc** [comment]
Thank you very much!
