### ISSUE TITLE
Using JVM Agent 2.1.1 in SOLR Docker image give no results

### ISSUE THREAD

**Issue by igittigitt** [jolokia/jolokia#768]
I am running my Solr server as a Docker container build from the official image from https://hub.docker.com/_/solr as version 9.6, running on OpenJDK 17.

I've installed the `jolokia-agent-jvm-2.1.1-javaagent.jar` into /opt/jolokia and added this to SOLR_OPTS variable:
`-javaagent:/opt/jolokia/jolokia-agent-jvm-2.1.1-javaagent.jar=port=8778,host=0.0.0.0`

I can see on the "Java Properties" of the Solr admin that it got loaded and could also curl to it using
curl localhost:8778/jolokia/search/
but i always get an empty answer, no metrics. JMX is enabled as well.

What do i do wrong?

**Comment by tadayosi** [comment]
Try:
curl localhost:8778/jolokia/version
or:
curl localhost:8778/jolokia/list

Do these return anything?

**Comment by igittigitt** [comment]
No,
`root@cff447ebb5f4:/opt/solr-9.6.0# curl -v localhost:8778/jolokia/version
*   Trying 127.0.0.1:8778...
* Connected to localhost (127.0.0.1) port 8778 (#0)
> GET /jolokia/version HTTP/1.1
> Host: localhost:8778
> User-Agent: curl/7.81.0
> Accept: */*
>
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server
`

**Comment by grgrzybek** [comment]
I checked outside of the container (by running standalone) and besides `SOLR_OPTS` env variable I had to set `SOLR_SECURITY_MANAGER_ENABLED=false`.

See the discussion under #449 where Elasticsearch was also run with Java Security Manager and I tried hard to configure proper permissions to allow Jolokia to open sockets and read from them...
It wasn't easy to convince Security Manager that javaagent is allowed to do all that stuff - but still I failed.

So I'm pretty sure you don't need Security Manager, especially because you can see this in Solr logs anyway:
```
WARNING: A command line option has enabled the Security Manager
WARNING: The Security Manager is deprecated and will be removed in a future release
```

**Comment by igittigitt** [comment]
You're genuis, man! That made it work:
`root@3a52b4c4784a:/opt/solr-9.6.0# curl -s localhost:8778/jolokia/version | jq
{
  "request": {
    "type": "version"
  },
  "value": {
    "agent": "2.1.1",
    "protocol": "8.0",
    "details": {
      "agent_version": "2.1.1",
      "agent_id": "7adf9f5f-jvm",
      "secured": false,
      "url": "http://172.29.1.3:8778/jolokia/"
    },
    "id": "7adf9f5f-jvm",
    "config": {
      "maxDepth": "15",
      "discoveryEnabled": "false",
      "maxCollectionSize": "0",
      "agentId": "7adf9f5f-jvm",
      "debug": "false",
      "historyMaxEntries": "10",
      "agentContext": "/jolokia",
      "maxObjects": "0",
      "debugMaxEntries": "100"
    },
    "info": {
      "proxy": {},
      "jmx": {}
    }
  },
  "status": 200,
  "timestamp": 1733514502
}
`
