### ISSUE TITLE
Unsupported protocol: jolokia Error when Application tries to Generate JmxConnector 

### ISSUE THREAD

**Issue by VictorCavichioli** [jolokia/jolokia#774]
Hi, I have a Spring boot maven application in Java 17 and this application needs to connect with another java application that is using jolokia, to avoid refactoring all the classes made using javax, I decided to follow this guide https://jolokia.org/reference/html/manual/clients.html#remote-jmx-example

In my pom.xml I have this dependency:

```xml
<dependency>
    <groupId>org.jolokia</groupId>
    <artifactId>jolokia-jsr160</artifactId>
    <version>1.7.1</version>
</dependency>
```

And in my code I have this:

```java
private static final String JMX_JOLOKIA_FORMAT_URL = "service:jmx:jolokia://%s:%d/jolokia";

# some other irrelevant code for this problem
JMXServiceURL jmxUrl;
Integer port;
if (isJolokiaEnabled)
{
    port = myJolokiaPort;
    jmxUrl = new JMXServiceURL(String.format(JMX_JOLOKIA_FORMAT_URL, host, port));
}

JMXConnector jmxConnector = JMXConnectorFactory.connect(jmxUrl, createJMXEnv());

```

But when it tries to connect, this error appears: Failed to create JMX connection with because of Unsupported protocol: jolokia, am I doing something wrong?

```java
private Map<String, Object> createJMXEnv()
    {
        Map<String, Object> env = new HashMap<>();
        String[] credentials = getCredentialsConfig();
        Map<String, String> tls = getTLSConfig();
        if (credentials != null)
        {
            env.put(JMXConnector.CREDENTIALS, credentials);
        }

        if (!tls.isEmpty())
        {
            for (Map.Entry<String, String> configEntry : tls.entrySet())
            {
                String key = configEntry.getKey();
                String value = configEntry.getValue();

                if (!value.isEmpty())
                {
                    System.setProperty(key, value);
                }
                else
                {
                    System.clearProperty(key);
                }
            }
            env.put("com.sun.jndi.rmi.factory.socket", new SslRMIClientSocketFactory());
        }
        return env;
    }
```

**Comment by VictorCavichioli** [comment]
@grgrzybek I see that you are involved in most of jolokia issues, do you know about this?

**Comment by grgrzybek** [comment]
Hello!

Sorry - I saw your message, but didn't have time (yet) to respond and check.

But quickly - Jolokia 1.7 is old version which uses `javax.` packages for Servlet API and should not be used with Spring Boot 3+ / JDK 17.

But most importantly - you're confusing `jolokia-jsr160` with `jolokia-jmx-adapter`.

The first one is used at server side, so clients can use Jolokia as kind of proxy for remote JMX server (which doesn't run Jolokia). See https://jolokia.org/reference/html/manual/proxy_mode.html.

`jolokia-jmx-adapter` is a _client_ jar, which includes `/META-INF/services/javax.management.remote.JMXConnectorProvider` which allows you to use JMX Connection URLs like `service:jmx:jolokia://localhost:8778/jolokia`. See https://jolokia.org/reference/html/manual/clients.html#remote-jmx-example.

I didn't check your particular scenario, but it should work.

**Comment by VictorCavichioli** [comment]
> jolokia-jmx-adapter

Hi @grgrzybek  !

No problem, thanks for quick response, I can describe a little bit more my use case, so I have a java application "A" that uses the jolokia to expose jmx to rest interface, which is working fine, but now I have another java application "B" that was designed using javax.management.remote things, that must connect with Jmx interface of application "A", as this "A" application does not exposes the jmx port anymore, just jolokia port (8778), I need to use this adapter to avoid a lot of refactoring, but I'm still trying to understand how it works.

I understand that 1.7.1 is really old, but I think the last available package in maven is 1.7.2, right? Is there any plan to include the new ones in maven? https://mvnrepository.com/artifact/org.jolokia/jolokia-jmx-adapter

BTW, I have downloaded the [jolokia-client-jmx-adapter-2.1.1.jar](https://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-client-jmx-adapter/2.1.1/jolokia-client-jmx-adapter-2.1.1.jar) and installed locally to include as maven dependency, but now I'm having this message here org.jolokia.client.exception.J4pRemoteException: Not Found, going deeply in debug mode I see that it failed because of a Parse exception "Invalid character '<' in 1:1", I see this too HttpResponseProxy{HTTP/1.1 404 Not Found [Content-Length: 50, Content-Type: text/html] ResponseEntityProxy{[Content-Type: text/html,Content-Length: 50,Chunked: false]}}, but I don't where this "<" is coming from, the url mount is apparently correct 

For tests purposes, I have a local instance of the "A" application using [jolokia-jvm-2.1.1-javaagent.jar](https://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-agent-jvm/2.1.1/jolokia-agent-jvm-2.1.1-javaagent.jar)

**Comment by VictorCavichioli** [comment]
Hi @grgrzybek !

I see that this example of documentation is missing something https://jolokia.org/reference/html/manual/clients.html#remote-jmx-example, well, the "Not found" problem I'm having is because this format <ip>:<port>/jolokia is not available and it's returning an html "<h1>404 Not Found</h1>No context found for request", what would be the main url format? Because from my quick studies of jolokia, I always need to pass and /read or /exec, and some other info, but these things would be included when the operation should be performed I guess, this example below from jolokia docs is exactly what I want to do:

```java
import javax.management.remote.*;
import javax.management.ObjectName;
import java.util.Arrays;

public class ConnectWithJolokiaDemo {
  public static void main(String[] args) throws Exception {
    Map<String, Object> options = new HashMap<>();
    // Add user & password if the Agent is secured:
    options.put(JMXConnector.CREDENTIALS, new String[] { "jolokia", "jolokia" });

    // https will be used if port number fits the pattern *443
    // or if options contains "jmx.remote.x.check.stub"->"true"
    JMXConnector connector = JMXConnectorFactory.connect(
        new JMXServiceURL("service:jmx:jolokia://localhost:8778/jolokia"),
        options);
    connector.connect();
    System.out.println("Memory used: " +
        connector.getMBeanServerConnection().getAttribute(
            ObjectName.getInstance("java.lang:type=Memory"),"HeapMemoryUsage"));
  }
}
```

**Comment by grgrzybek** [comment]
Hello

I'm glad you've found 99.9% working example ;)

It works after you switch from:
```
service:jmx:jolokia://localhost:7778/jolokia
```
to
```
service:jmx:jolokia://localhost:7778/jolokia/
```

That's something related to how JDK HTTP server handles contexts... and yes - documentation needs to be fixed ;)
