### ISSUE TITLE
Clarification on Using Jmx Notifications in Jolokia 2

### ISSUE THREAD

**Issue by VictorCavichioli** [jolokia/jolokia#778]
Hi, from what I understand in that documentation: https://jolokia.org/reference/html/manual/jolokia_protocol.html#notification-add

I'd be able to add a notification listener using java MBeanServerConnection().addNotificationListener, I have this code below, I'm using jolokia jvm agent 2.1.1 in server side and jolokia jmx adapter 2.1.1 in client side, using java 17 and spring boot 3:

```java
public void addStorageServiceListener(final UUID nodeID, final NotificationListener listener)
        {
            JMXConnector nodeConnection = myDistributedJmxConnectionProvider.getJmxConnector(nodeID);
            boolean isConnectionAvailable = validateJmxConnection(nodeConnection);
            if (isConnectionAvailable)
            {
                try
                {
                    nodeConnection.addConnectionNotificationListener(listener, null, null);
                    nodeConnection.getMBeanServerConnection().addNotificationListener(myStorageServiceObject, listener, null, null);
                }
                catch (InstanceNotFoundException | IOException e)
                {
                }
            }
```

But it's returning this error:

```
java.lang.UnsupportedOperationException: addNotificationListener not supported for Jolokia
```

Am I doing something wrong? The first step in the documentation says that I need to register a client and I'm doing this, but I don't understand where should I use this clientID to use .getMBeanServerConnection().addNotificationListener(), can you please clarify this?

**Comment by rhuss** [comment]
I'm not sure, but I think JMX Notification is not supported for Jolokia JSR-160 connectors, but only directly via Jolokia's REST-like API and in the JavaScript client library.

One reason for this is that JSR-160 support for Jolokia 1.x was developed parallel to Jolokia 2.0 (which included the new notification support).

I'm not so deep in the weeds anymore, but @skarsaune & @grgrzybek is my assessment correct ?

**Comment by skarsaune** [comment]
Correct, notifications were not part of the scope then. We can look into it.

**Comment by grgrzybek** [comment]
https://jolokia.org/reference/html/manual/jolokia_protocol.html#notification-add is about JSON protocol extension to support notifications.
Maybe we can clarify it a bit more in documentation (but not much more)...

The point is - Jolokia agent running within JVM exposes the MBeans over HTTP+JSON. Before Jolokia 2 you could execute operations, read/write attributes, search and list MBeans.
In Jolokia 2 you can additional register listeners using JavaScript and JSON within this JVM. Roughly after you:

1. register a client for notifications by sending to `<base-url>/notification/register` this JSON:
```json
{
  "type": "notification",
  "command": "register"
}
```
2. get a response with "client id" and mechanisms to retrieve the notifications:
```json
  "value": {
    "backend": {
      "pull": {
        "maxEntries": 100,
        "store": "jolokia:type=NotificationStore,agent=192.168.0.221-21185-7e985ce9-servlet"
      },
      "sse": {
        "backChannel.contentType": "text/event-stream",
        "backChannel.encoding": "UTF-8"
      }
    },
    "id": "d77475dc-c7a7-4f71-b988-52b7f0252ca3"
  },
```
3. register a listener for particular MBean using received "client id" by sending to `<base-url>/notification/add` this json:
```json
{
  "type": "notification",
  "command": "add",
  "client": "d77475dc-c7a7-4f71-b988-52b7f0252ca3",
  "mode": "pull",
  "mbean": "JMImplementation:type=MBeanServerDelegate",
  "filter": [],
  "handback": "id-1234"
}
```
4. get a response with "handler" (equals to `2` here):
```json
{
  "request": {
    "mode": "pull",
    "mbean": "JMImplementation:type=MBeanServerDelegate",
    "client": "d77475dc-c7a7-4f71-b988-52b7f0252ca3",
    "type": "notification",
    "handback": "id-1234",
    "command": "add"
  },
  "value": "2",
  "status": 200,
  "timestamp": 1702472334
}
```


you can get them (_open_) using:
```
$ curl -i -u jolokia:jolokia 'http://localhost:8080/jolokia/notification/open/d77475dc-c7a7-4f71-b988-52b7f0252ca3/sse'
HTTP/1.1 200
Cache-Control: private
Content-Type: text/event-stream;charset=UTF-8
Transfer-Encoding: chunked
Date: Wed, 13 Dec 2023 15:49:39 GMT

:
:
:
:
:
id: 363
data: {"dropped":0,"handle":"2","handback":null,"notifications":[{"timeStamp":1702482067031,"sequenceNumber":363,"userData":null,"mBeanName":{"objectName":"Catalina:J2EEApplication=none,J2EEServer=none,WebModule=\/\/localhost\/,name=jsp,type=JspMonitor"},"source":{"objectName":"JMImplementation:type=MBeanServerDelegate"},"message":"","type":"JMX.mbean.unregistered"}]}

id: 364
data: {"dropped":0,"handle":"2","handback":null,"notifications":[{"timeStamp":1702482067031,"sequenceNumber":364,"userData":null,"mBeanName":{"objectName":"Catalina:J2EEApplication=none,J2EEServer=none,WebModule=\/\/localhost\/,j2eeType=Filter,name=Tomcat WebSocket (JSR356) Filter"},"source":{"objectName":"JMImplementation:type=MBeanServerDelegate"},"message":"","type":"JMX.mbean.unregistered"}]}
...
```

each entry (in `text/event-stream` kind of response) contains notification data including `handle` id related to particular listener for chosen MBean.

So https://jolokia.org/reference/html/manual/jolokia_protocol.html#notification-add is about HTTP/JSON access to notifications within JVM.

On the other hand your example with `nodeConnection.getMBeanServerConnection().addNotificationListener()` is related to https://jolokia.org/reference/html/manual/architecture.html#proxy-mode where you effectively access one JVM through another JVM, where the one you use directly (proxy) accepts HTTP/JSON messages and translates them to actual JMX/RMI protocol to access the target JVM.

I hope this clarifies the picture.

Thanks @rhuss @skarsaune for feedback!

**Comment by VictorCavichioli** [comment]
Hi guys!

Thanks for the clarification and quick response!

**Comment by skarsaune** [comment]
@VictorCavichioli : I assume we would have to make the adapter stateful and see what frameworks we have available or need to add to support consuming server side events.

**Comment by grgrzybek** [comment]
I agree with @skarsaune - ultimately, the target JVM would need to store the notification events to be picked up in _pull_ style from JVM where Jolokia agent is present...
I don't think it's an easy implementation, but if you have any prototype, I'd be happy to review it ;)

**Comment by VictorCavichioli** [comment]
Hi @rhuss @grgrzybek and @skarsaune,

Sorry for being late in my response, I was planning to take a deeply look into that, but I received other priorities, anyway, I understand that it would be really hard, so we decided to use the notifications in the way you suggested and it's apparently working fine, thanks for the clarification!

**Comment by grgrzybek** [comment]
Thanks for your feedback @VictorCavichioli !
