### ISSUE TITLE
Create a JBoss Forge plugin

### ISSUE THREAD

**Issue by rhuss** [jolokia/jolokia#81]
Similar to the existing Roo plugin, a JBoss Forge plugin would be nice.

An initial version has been checked in in the branch `jboss-forge`

**Comment by tadayosi** [comment]
I'm not sure if JBoss Forge is still the current state of the art. Maybe we can just close it. @grgrzybek @rhuss WDYT?

**Comment by davsclaus** [comment]
yes close it
