### ISSUE TITLE
Extract JolokiaServer in an own module

### ISSUE THREAD

**Issue by rhuss** [jolokia/jolokia#89]
Since `JolokiaServer`, the agent part which uses Oracle's internal HTTP-Server for exposing the agent is already used in two places (the JVM-Agent which allows e.g. for attaching to running Java processes via the Attach API and the Spring `<jolokia:agent>` support) and makes sense to extract it and to prepare the public interface (which currently wasn't intended for public use despite the fact that many methods are declared as public).

See also #87 for an in depth discussion for this issue.

**Comment by grgrzybek** [comment]
I think this can be set as fixed in 2.0. See https://jolokia.org/libraries.html

**Comment by rhuss** [comment]
Yes, I think that makes sense, also because it's quite an old issue. In which library actually went the `JolokiaServer` ?

**Comment by grgrzybek** [comment]
`JolokiaServer` is a class using `com.sun.net.httpserver.HttpServer` and it's part of `org.jolokia:jolokia-agent-jvm` (previously - `org.jolokia:jolokia-jvm`)
