### ISSUE TITLE
Create a Spring MVC controller for Jolokia

### ISSUE THREAD

**Issue by rhuss** [jolokia/jolokia#91]
For extending Jolokia's Spring support, it would be nice to have a dedicated Jolokia Controller which can be hooked into the DispatcherServlet (as an alternative to using an own HTTP server with `<jolokia:agent>`)

**Comment by grgrzybek** [comment]
We have now much more flexibility with Spring MVC than we had in 2013... Jolokia servlet is working perfectly with Spring's `org.springframework.web.context.support.AnnotationConfigWebApplicationContext` and even old `org.springframework.web.servlet.handler.SimpleServletHandlerAdapter`.
I'd close this one.
